---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
knitr::opts_knit$set(root.dir = '/home/yuzhao1/gca/yuzhao1/work/gca_rna/')
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')

library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
source('~/yuzhao1/scripts/plot.R')
```


```{r, include = F, eval=F}
epithelial <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial1.rds')
```

```{r, eval=F}
# save epithelial1 again after processing, fix its clustering results. Don't modify again
# saveRDS(epithelial, '~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial1.rds')
```


```{r}
# filter LQ cells from previous clustering results, and then remove precious labels, from epithelial1 to epithelial2
# LQ: remove plasma and other immune doublets, isolated clusters without a specific marker (e.g. a cluster with cells in mixed EC states)
xx <- Cells(epithelial)[which(!epithelial$seurat_clusters_res0.5 %in% c('10', '14', '18'))] 
epithelial_filtered <- subset(epithelial, cells = xx)
columns_to_remove <- grep("seurat_cluster", names(epithelial_filtered@meta.data))
epithelial_filtered@meta.data <- epithelial_filtered@meta.data[,-columns_to_remove]
columns_to_remove <- grep("RNA_snn_", names(epithelial_filtered@meta.data))
epithelial_filtered@meta.data <- epithelial_filtered@meta.data[,-columns_to_remove]
```


```{r}
df_annotation_res0.5 <- list(
'0' = 'EC1-2',
'1' = 'EC1-2',
'2' = 'EC2-1',
'3' = 'Goblet2',
'4' = 'TA',
'5' = 'Goblet1',
'6' = 'EC2-2',
'7' = 'EC1-1',
'8' = 'Stem',
'9' = 'Tuft',
'11' = 'EC2-1',
'12' = 'M-like',
'13' = 'BEST4',
'15' = 'EEC',
'16' = 'EC1-2',
'17' = 'Paneth'
)
epithelial$anno1 <- unlist(mapvalues(as.character(epithelial$seurat_clusters_res0.5), from = names(df_annotation_res0.5), to = df_annotation_res0.5))
```

```{r, eval=F}
# # save epithelial2 again after second round of processing
# saveRDS(epithelial, '~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial2.rds')
# saveRDS(epithelial_filtered, '~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds') (kept clustering and umaps results from epithelial2)
```



```{r, eval=F}
# save epithelial2 again after second round of processing
saveRDS(epithelial, '~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
```


```{r, eval=F}
epithelial <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
```

```{r}
# # wirte umap
# df <- data.frame(epithelial@meta.data)
# df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
# df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
# 
# write.table(df[, c('embedding1','embedding2')], '~/yuzhao1/work/final_RC2rna/velocity/epithelial/umap.csv', col.names = F,
#             row.names=F, sep = ',')
# 
# # update umap from python
# umaps <- read.table('~/yuzhao1/work/final_RC2rna/velocity/epithelial/umap.csv', header = F, sep = ',')
# colnames(umaps) <- c('UMAP_1', 'UMAP_2')
# epithelial@reductions$harmony_umap@cell.embeddings <- as.matrix(umaps)

```

```{r}
write.table(epithelial@reductions$harmony_umap@cell.embeddings,
            '~/yuzhao1/work/final_RC2rna/celloracle/all/original_umap_epi.csv', 
            col.names = T, row.names=T, sep = ',')

```

### workflow


```{r, include = F, eval=F}
# epithelial3 has all been preprocessed, but kept using the embedding and clustering results of epithelial2 (best accuray for cell-type markers)
epithelial <- NormalizeData(epithelial)
epithelial <- FindVariableFeatures(epithelial, selection.method = "vst", nfeatures = 2000)
epithelial <- ScaleData(epithelial, vars.to.regress = c('percent.mt', 'nCount_RNA', 'CC.Difference'))
epithelial <- RunPCA(epithelial, npcs = 50)
epithelial <- RunHarmony(epithelial, group.by.vars = 'Patient_ID', max.iter.harmony = 20)
epithelial <- FindNeighbors(epithelial, reduction = 'harmony', dims = 1:30)

# this specific embedding captures the clustering results very well.
# epithelial <- RunUMAP(epithelial,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap', 
#                       min.dist = 0.5, n.neighbors = 50, seed.use = 5,
#                       reduction.key = 'UMAP_')

epithelial <- FindClusters(epithelial, resolution = 0.5)
epithelial$seurat_clusters_res0.5 <- Idents(epithelial)


```

```{r}
ElbowPlot(epithelial, ndims = 50)
```


```{r}
xx <- list()

require(foreach)
max_iterations <- 24
opts <- list()
pb <- txtProgressBar(min = 0, max = max_iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

# set parallel backend
nCores = 24
cl <- parallel::makeCluster(nCores)
doSNOW::registerDoSNOW(cl)
getDoParWorkers()
getDoParName()

# do parallel computing
foreach::foreach(cluster=as.character(1:24), .packages = c('patchwork', "dplyr", "Seurat"), 
                 .options.snow = opts, .inorder = F) %dopar% {
  dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
  xx[[cluster]] <- FindMarkers(epithelial, ident.1 = cluster, min.pct = 0.2, logfc.threshold = 0.5, group.by = 'seurat_clusters_res0.5')
  # saveRDS(xx[[cluster]], paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/epithelial1_res1.5/cluster_', cluster, '.rds'))
                 }

parallel::stopCluster(cl)
```

```{r}
xx <- list()
```

```{r}
# do parallel computing
for(cluster in unique(epithelial$seurat_clusters_res0.5)){
  xx[[cluster]] <- FindMarkers(epithelial, ident.1 = cluster, min.pct = 0.2, logfc.threshold = 1, group.by = 'seurat_clusters_res0.5')
  saveRDS(xx[[cluster]], paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/epithelial3_res0.5/cluster_', cluster, '.rds'))
}


```

```{r}
cluster <- '18'
View(readRDS(paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/epithelial3_res1.5/cluster_', cluster, '.rds')))
```




### Check clustering results

```{r}
# epithelial <- RunUMAP(epithelial,  dims = 1:50, reduction = 'harmony', reduction.name = 'harmony_umap',
#                       min.dist = 0.5, n.neighbors = 50, seed.use = 42,
#                       repulsion.strength = 1.2, negative.sample.rate = 5, 
#                       reduction.key = 'UMAP_')

epithelial <- RunUMAP(epithelial,  dims = 1:50, reduction = 'harmony', reduction.name = 'harmony_umap',
                      min.dist = 0.3, n.neighbors = 50, seed.use = 5,
                      repulsion.strength = 1.2, negative.sample.rate = 5, 
                      reduction.key = 'UMAP_')

# epithelial <- RunUMAP(epithelial,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap',
#                       min.dist = 0.5, n.neighbors = 30, seed.use = 0, negative.sample.rate = 5,
#                       repulsion.strength = 1, reduction.key = 'UMAP_')

# epithelial <- RunUMAP(epithelial,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap',
#                       min.dist = 0.5, n.neighbors = 50, seed.use = 34196, 
#                       repulsion.strength = 1.0, n.epochs = 200, negative.sample.rate = 50, 
#                       reduction.key = 'UMAP_')

```


```{r, fig.height=9, fig.width=8.5}
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- epithelial$anno1
plot_df_umap_custom(df, show.label = 'name')
```

```{r}
# wirte umap
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2

write.table(df[, c('embedding1','embedding2')], '~/yuzhao1/work/final_RC2rna/velocity/epithelial/umap.csv', col.names = F,
            row.names=F, sep = ',')
```

```{r, fig.height=9, fig.width=8.5}
df <- data.frame(epithelial@meta.data)
# df$embedding1 <- umaps$V1
# df$embedding2 <- umaps$V2
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- epithelial$anno1
p<-plot_df_umap_custom(df, show.label = 'name')
p

png('~/yuzhao1/work/final_RC2rna/annotation/plots/umap_epithelial.png',res = 300, height = 2000, width = 1800)
p
dev.off()
```

```{r, fig.height=13, fig.width=12}
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
# df$embedding1 <- umaps$V1
# df$embedding2 <- umaps$V2
df$cluster_name <- epithelial$anno1
p<- plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
p
png('~/yuzhao1/work/final_RC2rna/annotation/plots/umap_epithelial_loc.png',res = 300, height = 3600, width = 3000)
plot_df_umap_custom(df, show.label = 'na') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```


```{r, fig.height=13, fig.width=12}
epithelial@meta.data$Sample_ID_Corrected <- factor(epithelial@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- epithelial$anno1

p<- plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
p
png('~/yuzhao1/work/final_RC2rna/annotation/plots/umap_epithelial_sample.png',res = 300, height = 5000, width = 8000)
p
dev.off()
```

#### Check specific markers

```{r}
xx <- FindMarkers(epithelial, ident.1 = 'EC2-3', ident.2 = c('EC2-1','EC2-2'), min.pct = 0.2, logfc.threshold = 0.5, group.by = 'anno1')
```

```{r}
View(xx)
```


```{r}
gene <- 'OLFM4'
feature <- gene
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) 

VlnPlot(epithelial, gene, group.by = 'anno1', pt.size = 0)

```


```{r}
feature <- 'DEFA5'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```


```{r}
feature <- 'LGR5'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'POU2F3'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'CHGA'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'EPCAM'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'ADH1C'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)+
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```


```{r, fig.width=10}
VlnPlot(epithelial, 'MUC2', group.by = 'seurat_clusters_res0.5', pt.size = 0)
```






```{r}
feature <- 'CEACAM7'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```


```{r, fig.height=10, fig.width=10}
feature <- 'MUC2'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```


```{r}
feature <- 'FABP6'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'CD55'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'CCL20'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'BEST4'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r, fig.width=10}
VlnPlot(epithelial, 'VIM', group.by = 'anno1', pt.size = 0)
```


```{r}
feature <- 'CD55'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```


```{r, fig.width=10}
VlnPlot(epithelial, 'DEFA5', group.by = 'seurat_clusters_res0.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(epithelial, 'IGHA1', group.by = 'seurat_clusters_res0.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(epithelial, 'FABP2', group.by = 'seurat_clusters_res0.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(epithelial, 'CCL20', group.by = 'seurat_clusters_res0.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(epithelial, 'MMP1', group.by = 'seurat_clusters_res0.5', pt.size = 0)
```









### check stem cell subclusters

```{r}
stem <- subset(epithelial, cells = Cells(epithelial)[epithelial$anno1 %in% c('Stem', 'Stem1', 'Stem2')])
stem <- NormalizeData(stem)
stem <- FindVariableFeatures(stem, selection.method = "vst", nfeatures = 2000)
stem <- ScaleData(stem, vars.to.regress = c('percent.mt', 'nCount_RNA', 'CC.Difference'))
stem <- RunPCA(stem, npcs = 50)
stem <- RunHarmony(stem, group.by.vars = 'Patient_ID', max.iter.harmony = 20)
stem <- FindNeighbors(stem, reduction = 'harmony', dims = 1:30)

# this specific embedding captures the clustering results very well.
stem <- RunUMAP(stem,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap',
                      min.dist = 0.5, n.neighbors = 50, seed.use = 5,
                      reduction.key = 'UMAP_')


columns_to_remove <- grep("seurat_cluster", names(stem@meta.data))
stem@meta.data <- stem@meta.data[,-columns_to_remove]
columns_to_remove <- grep("RNA_snn_", names(stem@meta.data))
stem@meta.data <- stem@meta.data[,-columns_to_remove]

stem <- FindClusters(stem, resolution = 0.2)
stem$seurat_clusters_res0.2 <- Idents(stem)
```



```{r}
DimPlot(stem, group.by = 'anno1')
DimPlot(stem, group.by = 'biopsy_location')
DimPlot(stem, group.by = 'seurat_clusters_res0.2')
# bq.stem2 <- Cells(stem)[stem$seurat_clusters_res0.2=='2']
# bq.stem1 <- Cells(stem)[stem$seurat_clusters_res0.2=='0' | stem$seurat_clusters_res0.2=='1']
```

```{r}
saveRDS(stem, '~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3_stem.rds')
```


```{r}
### update epithelial meta data with stem cell subclusters
epithelial@meta.data[bq.stem1, 'anno1'] <- 'Stem1'
epithelial@meta.data[bq.stem2, 'anno1'] <- 'Stem2'
```

```{r, fig.width=12}
DimPlot(epithelial, group.by = 'anno1')
DimPlot(epithelial, group.by = 'anno1', split.by = 'biopsy_location')
table(epithelial@meta.data[, c('anno1', 'biopsy_location')])
```

```{r}
seurat$anno2 <- seurat$anno1
seurat$anno1[seurat$anno1 %in% c("Stem1", "Stem2")] <- 'Stem'
```

```{r}
### update anno1_loc
seurat <- epithelial
seurat$anno1_loc <- paste0(seurat$anno1, '-', seurat$biopsy_location)
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2") & seurat$biopsy_location =='POU'] <- 'EC-POU1'
seurat$anno1_loc[seurat$anno1 %in% c("EC2-1", "EC2-2") & seurat$biopsy_location =='POU'] <- 'EC-POU2'
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='PP'] <- 'EC-PP'
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='TI'] <- 'EC-TI'
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='AC'] <- 'EC-AC'

seurat$anno1_loc[seurat$anno1 %in% c("Goblet1", "Goblet2") & seurat$biopsy_location =='POU'] <- 'Goblet-POU'
seurat$anno1_loc[seurat$anno1 %in% c("Goblet1", "Goblet2") & seurat$biopsy_location =='PP'] <- 'Goblet-PP'
seurat$anno1_loc[seurat$anno1 %in% c("Goblet1", "Goblet2") & seurat$biopsy_location =='TI'] <- 'Goblet-TI'
seurat$anno1_loc[seurat$anno1 %in% c("Goblet1", "Goblet2") & seurat$biopsy_location =='AC'] <- 'Goblet-AC'

seurat$anno1_loc[seurat$anno2 %in% c("Stem1") & seurat$biopsy_location =='POU'] <- 'Stem-POU1'
seurat$anno1_loc[seurat$anno2 %in% c("Stem2") & seurat$biopsy_location =='POU'] <- 'Stem-POU2'
seurat$anno1_loc[seurat$anno1 %in% c("Stem1", "Stem2") & seurat$biopsy_location =='PP'] <- 'Stem-PP'
seurat$anno1_loc[seurat$anno1 %in% c("Stem1", "Stem2") & seurat$biopsy_location =='TI'] <- 'Stem-TI'
seurat$anno1_loc[seurat$anno1 %in% c("Stem1", "Stem2") & seurat$biopsy_location =='AC'] <- 'Stem-AC'
```



```{r}
saveRDS(seurat, '~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
```

































