---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')

library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
# immune <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/immune2.rds')
```

```{r}
# # subset immune2 to t,b,myeloid based on res1.5
# cs.t <- as.character(c(0,3,6,7,8,11,12,13,23,28))
# cs.mye <- as.character(c(14,15,16,19,21,22))
# cs.b <- as.character(c(1,2,4,5,9,10,17,18,20,24,25,26,27,29))
# tcell <- subset(immune, cells = Cells(immune)[which(immune$seurat_clusters_res1.5 %in% cs.t)])
# myeloid <- subset(immune, cells = Cells(immune)[which(immune$seurat_clusters_res1.5 %in% cs.mye)])
# bcell <- subset(immune, cells = Cells(immune)[which(immune$seurat_clusters_res1.5 %in% cs.b)])
```

```{r}
# saveRDS(immune, '~/yuzhao1/work/final_RC2rna/annotation/rds/immune2.rds') 
# saveRDS(tcell, '~/yuzhao1/work/final_RC2rna/annotation/rds/tcell1.rds') 
# saveRDS(bcell, '~/yuzhao1/work/final_RC2rna/annotation/rds/bcell1.rds') 
# saveRDS(myeloid, '~/yuzhao1/work/final_RC2rna/annotation/rds/myeloid1.rds') 
```


```{r}
# # decide whether to remove clusters
# columns_to_remove <- grep("seurat_cluster", names(immune@meta.data))
# immune@meta.data <- immune@meta.data[,-columns_to_remove]
# columns_to_remove <- grep("RNA_snn_", names(immune@meta.data))
# immune@meta.data <- immune@meta.data[,-columns_to_remove]
```


```{r}
# # filter LQ cells from previous clustering results, and then remove precious labels, from immune1 to immune2
# # LQ: remove immune-epithelial doublets
# xx <- Cells(immune)[which(!immune$seurat_clusters_res1.5 %in% c('18', '22', '27'))]
# immune_filtered <- subset(immune, cells = xx)
# columns_to_remove <- grep("seurat_cluster", names(immune_filtered@meta.data))
# immune_filtered@meta.data <- immune_filtered@meta.data[,-columns_to_remove]
# columns_to_remove <- grep("RNA_snn_", names(immune_filtered@meta.data))
# immune_filtered@meta.data <- immune_filtered@meta.data[,-columns_to_remove]
```


```{r, eval=F}
# # save immune2 again after second round of processing
# saveRDS(immune, '~/yuzhao1/work/final_RC2rna/annotation/rds/immune1.rds')
# saveRDS(immune_filtered, '~/yuzhao1/work/final_RC2rna/annotation/rds/immune2.rds') 
```


```{r, eval=F}
# # filter based on results of subsets
# immune <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/immune2.rds')
# tcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/tcell2.rds')
# bcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/bcell3.rds')
# myeloid <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/myeloid3.rds')
# xx <- c(Cells(tcell), Cells(bcell), Cells(myeloid))
# xx.anno1 <- c(tcell$anno1, bcell$anno1, myeloid$anno1)
# 
# immune_filtered <- subset(immune, cells = xx)
# columns_to_remove <- grep("seurat_cluster", names(immune_filtered@meta.data))
# immune_filtered@meta.data <- immune_filtered@meta.data[,-columns_to_remove]
# columns_to_remove <- grep("RNA_snn_", names(immune_filtered@meta.data))
# immune_filtered@meta.data <- immune_filtered@meta.data[,-columns_to_remove]
# 
# immune_filtered$anno1 <- xx.anno1
# saveRDS(immune_filtered, '~/yuzhao1/work/final_RC2rna/annotation/rds/immune3.rds') 

```

```{r}
# saveRDS(immune, '~/yuzhao1/work/final_RC2rna/annotation/rds/immune3.rds') 
immune <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/immune3.rds')
```


```{r}
# ### update anno1_loc
# seurat <- immune
# seurat$anno1_loc <- paste0(seurat$anno1, '-', seurat$biopsy_location)
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD4 Trm", "CD103- CD4 Trm", "CD4 Tcm", "Treg") & seurat$biopsy_location =='POU'] <- 'CD4T-POU'
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD4 Trm", "CD103- CD4 Trm", "CD4 Tcm", "Treg") & seurat$biopsy_location =='PP'] <- 'CD4T-PP'
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD4 Trm", "CD103- CD4 Trm", "CD4 Tcm", "Treg") & seurat$biopsy_location =='TI'] <- 'CD4T-TI'
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD4 Trm", "CD103- CD4 Trm", "CD4 Tcm", "Treg") & seurat$biopsy_location =='AC'] <- 'CD4T-AC'
# 
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD8 Trm", "KLRG1+ CD8 Trm") & seurat$biopsy_location =='POU'] <- 'CD8T-POU'
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD8 Trm", "KLRG1+ CD8 Trm") & seurat$biopsy_location =='PP'] <- 'CD8T-PP'
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD8 Trm", "KLRG1+ CD8 Trm") & seurat$biopsy_location =='TI'] <- 'CD8T-TI'
# seurat$anno1_loc[seurat$anno1 %in% c("CD103+ CD8 Trm", "KLRG1+ CD8 Trm") & seurat$biopsy_location =='AC'] <- 'CD8T-AC'
# 
# # saveRDS(seurat, '~/yuzhao1/work/final_RC2rna/annotation/rds/immune3.rds')
```

### workflow


```{r, include = F, eval=F}
# immune3 has all been preprocessed, but kept using the embedding and clustering results of immune2 (best accuray for cell-type markers)
immune <- NormalizeData(immune)
immune <- FindVariableFeatures(immune, selection.method = "vst", nfeatures = 2000)
immune <- ScaleData(immune, vars.to.regress = c('percent.mt', 'nCount_RNA', 'CC.Difference'))
immune <- RunPCA(immune, npcs = 50)
immune <- RunHarmony(immune, group.by.vars = 'Patient_ID', max.iter.harmony = 20)
immune <- FindNeighbors(immune, reduction = 'harmony', dims = 1:50)

# this specific embedding captures the clustering results very well.
immune <- RunUMAP(immune,  dims = 1:50, reduction = 'harmony', reduction.name = 'harmony_umap',
                      min.dist = 0.5, n.neighbors = 50, seed.use = 0,
                      reduction.key = 'UMAP_')

immune <- FindClusters(immune, resolution = 0.2)
immune$seurat_clusters_res0.2 <- Idents(immune)

immune <- FindClusters(immune, resolution = 0.3)
immune$seurat_clusters_res0.3 <- Idents(immune)

immune <- FindClusters(immune, resolution = 0.5)
immune$seurat_clusters_res0.5 <- Idents(immune)

immune <- FindClusters(immune, resolution = 0.6)
immune$seurat_clusters_res0.6 <- Idents(immune)

immune <- FindClusters(immune, resolution = 0.7)
immune$seurat_clusters_res0.7 <- Idents(immune)

immune <- FindClusters(immune, resolution = 0.8)
immune$seurat_clusters_res0.8 <- Idents(immune)

immune <- FindClusters(immune, resolution = 1)
immune$seurat_clusters_res1 <- Idents(immune)

immune <- FindClusters(immune, resolution = 1.2)
immune$seurat_clusters_res1.2 <- Idents(immune)

immune <- FindClusters(immune, resolution = 1.5)
immune$seurat_clusters_res1.5 <- Idents(immune)

immune <- FindClusters(immune, resolution = 2)
immune$seurat_clusters_res2 <- Idents(immune)

immune <- FindClusters(immune, resolution = 2.5)
immune$seurat_clusters_res2.5 <- Idents(immune)
```

```{r}
ElbowPlot(immune, ndims = 50)
```


```{r}
xx <- list()

require(foreach)
max_iterations <- 4
opts <- list()
pb <- txtProgressBar(min = 0, max = max_iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

# set parallel backend
nCores = 4
cl <- parallel::makeCluster(nCores)
doSNOW::registerDoSNOW(cl)
getDoParWorkers()
getDoParName()

# do parallel computing
foreach::foreach(cluster=as.character(22,23,27,30), .packages = c('patchwork', "dplyr", "Seurat"), 
                 .options.snow = opts, .inorder = F) %dopar% {
  dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
  xx[[cluster]] <- FindMarkers(immune, ident.1 = cluster, min.pct = 0.2, logfc.threshold = 0.5, group.by = 'seurat_clusters_res0.5')
  # saveRDS(xx[[cluster]], paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/immune1_res1.5/cluster_', cluster, '.rds'))
                 }

parallel::stopCluster(cl)
```

```{r}
xx <- list()
```

```{r}
# do parallel computing
clusters_to_test <- unique(immune$seurat_clusters_res1.5)
# clusters_to_test <- c('14')
for(cluster in clusters_to_test ){
  xx[[cluster]] <- FindMarkers(immune, ident.1 = cluster, min.pct = 0.2, logfc.threshold = 1, group.by = 'seurat_clusters_res1.5')
  saveRDS(xx[[cluster]], paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/immune1_res1.5/cluster_', cluster, '.rds'))
}


```

```{r}
cluster <- '15'
View(readRDS(paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/immune1_res1.5/cluster_', cluster, '.rds')))
```


```{r}
# quickly check marker
feature <- 'HLA-DRA'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)

VlnPlot(immune, feature, group.by = 'seurat_clusters_res1.5', pt.size = 0)

```


### Check clustering results

```{r}
# immune <- RunUMAP(immune,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap', 
#                       min.dist = 0.5, n.neighbors = 50, seed.use = 34196,
#                       repulsion.strength = 1.1,
#                       reduction.key = 'UMAP_')

# immune <- RunUMAP(immune,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap',
#                       min.dist = 0.1, n.neighbors = 10, reduction.key = 'UMAP_',
#                       seed.use = 34196, n.epochs = 500,
#                       set.op.mix.ratio = 0.5, local.connectivity = 2, repulsion.strength = 0.5, negative.sample.rate = 20,
#                       spread = 0.5)

immune <- RunUMAP(immune,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap',
                      min.dist = 0.3, n.neighbors = 30, seed.use = 5, 
                      repulsion.strength = 1.0, n.epochs = 200, negative.sample.rate = 5, 
                      reduction.key = 'UMAP_')

```


```{r, fig.height=9, fig.width=8.5}
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- immune$seurat_clusters_res1.5
plot_df_umap_custom(df, show.label = 'name')
```

```{r, fig.height=9, fig.width=8.5}
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- immune$anno1
p<-plot_df_umap_custom(df, show.label = 'number')
p

png('~/yuzhao1/work/final_RC2rna/annotation/plots/umap_immune.png',res = 300, height = 2300, width = 2000)
p
dev.off()
```

```{r, fig.height=13, fig.width=12}
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- immune$anno1
p<- plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
p
png('~/yuzhao1/work/final_RC2rna/annotation/plots/umap_immune_loc.png',res = 300, height = 3000, width = 3000)
plot_df_umap_custom(df, show.label = 'na') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```

```{r, fig.height=13, fig.width=12}
immune@meta.data$Sample_ID_Corrected <- factor(immune@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- immune$anno1

p<- plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
p
png('~/yuzhao1/work/final_RC2rna/annotation/plots/umap_immune_sample.png',res = 300, height = 5000, width = 8000)
p
dev.off()
```


#### Check specific markers

```{r}
feature <- 'FCGR3A'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```


```{r}
feature <- 'MKI67'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```



```{r}
feature <- 'IGHA1'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r, fig.width=10}
VlnPlot(immune, 'IGHA1', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r}
feature <- 'XBP1'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r, fig.width=10}
VlnPlot(immune, 'IGHG1', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r}
feature <- 'IGKC'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'IGLC3'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'CD3D'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```



```{r}
feature <- 'IGKC'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r, fig.width=10}
VlnPlot(immune, 'IGLL5', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```


```{r, fig.width=10}
VlnPlot(immune, 'CD3D', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(immune, 'IGHA1', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(immune, 'FABP2', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(immune, 'CCL20', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r, fig.width=10}
VlnPlot(immune, 'IGHA1', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```



```{r}
cluster <- '24'
View(readRDS(paste0('~/yuzhao1/work/final_RC2rna/annotation/markers/immune1_res1.5/cluster_', cluster, '.rds')))
```

```{r}
xx <- FindMarkers(immune, ident.1 = '6', ident.2 = c('1', '4', '5'), min.pct = 0.2, logfc.threshold = 1, group.by = 'seurat_clusters_res1.5')
```


```{r, fig.width=10}
VlnPlot(immune, 'XBP1', group.by = 'seurat_clusters_res1.5', pt.size = 0)
```

```{r}
feature <- 'IL7R'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```


```{r}
feature <- 'XBP1'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'ZBTB16'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'G0S2'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)

VlnPlot(immune, feature, group.by = 'seurat_clusters_res1.5', pt.size = 0)

```
