---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
knitr::opts_knit$set(root.dir = '/home/yuzhao1/gca/yuzhao1/work/gca_rna/')
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')

library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
gut_raw <- readRDS('~/yuzhao1/work/final_RC2rna/preprocessing/RC2rna_all24samples_removedAmbientRNA_calculatedDoubletScores_seurat_filtered.rds')
epithelial <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
immune <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/immune3.rds')
others <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/others3.rds')
```

```{r}
tcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/tcell2.rds')
bcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/bcell3.rds')
myeloid <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/myeloid3.rds')
```

```{r}
# create and save a cellname-lineage-anno1 csv file
CellAnnotation <- data.frame('ID' =  c(Cells(epithelial), Cells(tcell), Cells(bcell), Cells(myeloid), Cells(others)),
                             'lineage' = c(rep('epithelial', ncol(epithelial)),
                                           rep('tcell', ncol(tcell)),
                                           rep('bcell', ncol(bcell)),
                                           rep('myeloid', ncol(myeloid)),
                                           rep('others', ncol(others))),
                             'anno1' = c(epithelial$anno1, tcell$anno1, bcell$anno1, myeloid$anno1, others$anno1),
                             row.names = NULL)

```



```{r, eval=F}
# filter based on results of subsets
gut_filtered <- subset(gut_raw, cells = CellAnnotation$ID)
gut_filtered$lineage <- CellAnnotation$lineage
gut_filtered$anno1 <- CellAnnotation$anno1
```

```{r}
gut_filtered$biopsy_location[which(gut_filtered$Sample_ID == "HA02-TI")] <- 'AC'
gut_filtered$biopsy_location[which(gut_filtered$Sample_ID == "HA02-AC")] <- 'TI'
gut_filtered$Sample_ID_Corrected <- mapvalues(gut_filtered$Sample_ID,
                                         from = c("HA02-TI", "HA02-AC"),
                                         to = c("HA02-AC", "HA02-TI"))
```


```{r, eval=F}
saveRDS(gut_filtered, '~/yuzhao1/work/final_RC2rna/annotation/rds/gut_filtered.rds')
write.table(gut_filtered@meta.data, '~/yuzhao1/work/final_RC2rna/metadata/CellMetadata.csv',
            col.names = F, row.names=F, sep = ',')
```

```{r}
gut_filtered <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/gut_filtered.rds')
```

```{r}
# update anno1s from subsets
# immune union should be updated in immune notebook

epithelial <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
tcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/tcell2.rds')
bcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/bcell3.rds')
myeloid <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/myeloid3.rds')
others <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/others3.rds')

CellAnnotation <- data.frame('ID' =  c(Cells(epithelial), Cells(tcell), Cells(bcell), Cells(myeloid), Cells(others)),
                             'anno1' = c(epithelial$anno1, tcell$anno1, bcell$anno1, myeloid$anno1, others$anno1),
                             'anno1_loc' = c(epithelial$anno1_loc, tcell$anno1_loc, bcell$anno1_loc, myeloid$anno1_loc, others$anno1_loc),
                             row.names = NULL)

idx <- match(CellAnnotation$ID, Cells(gut_filtered))
gut_filtered$anno1[idx] <- CellAnnotation$anno1
gut_filtered$anno1_loc[idx] <- CellAnnotation$anno1_loc
```

```{r}
gut_filtered$anno1_loc[gut_filtered$anno2 %in% c("Stem1") & gut_filtered$biopsy_location =='POU'] <- 'Stem-POU1'
gut_filtered$anno1_loc[gut_filtered$anno2 %in% c("Stem2") & gut_filtered$biopsy_location =='POU'] <- 'Stem-POU2'
gut_filtered$anno1_loc[gut_filtered$anno1 %in% c("Stem1", "Stem2") & gut_filtered$biopsy_location =='PP'] <- 'Stem-PP'
gut_filtered$anno1_loc[gut_filtered$anno1 %in% c("Stem1", "Stem2") & gut_filtered$biopsy_location =='TI'] <- 'Stem-TI'
gut_filtered$anno1_loc[gut_filtered$anno1 %in% c("Stem1", "Stem2") & gut_filtered$biopsy_location =='AC'] <- 'Stem-AC'
```



### workflow


```{r, include = F, eval=F}
gut_filtered <- NormalizeData(gut_filtered)
gut_filtered <- FindVariableFeatures(gut_filtered, selection.method = "vst", nfeatures = 2000)
gut_filtered <- ScaleData(gut_filtered, vars.to.regress = c('percent.mt', 'nCount_RNA', 'CC.Difference'))
gut_filtered <- RunPCA(gut_filtered, npcs = 50)
gut_filtered <- RunHarmony(gut_filtered, group.by.vars = 'Patient_ID', max.iter.harmony = 20)
gut_filtered <- FindNeighbors(gut_filtered, reduction = 'harmony', dims = 1:50)
 
gut_filtered <- RunUMAP(gut_filtered,  dims = 1:50, reduction = 'harmony', reduction.name = 'harmony_umap',
                      min.dist = 0.5, n.neighbors = 50, seed.use = 0,
                      reduction.key = 'UMAP_')
```


### Check clustering results

```{r, fig.height=9, fig.width=8.5}
df <- data.frame(gut_filtered@meta.data)
df$embedding1 <- data.frame(gut_filtered@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(gut_filtered@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- gut_filtered$anno1
p<-plot_df_umap_custom(df, show.label = 'number')
p

png('~/yuzhao1/work/final_RC2rna/annotation/plots/1umap_all.png',res = 300, height = 3000, width = 2600)
p
dev.off()
```

```{r, fig.height=13, fig.width=12}
df <- data.frame(gut_filtered@meta.data)
df$embedding1 <- data.frame(gut_filtered@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(gut_filtered@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- gut_filtered$anno1
p<- plot_df_umap_custom(df, show.label = 'na') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
p
png('~/yuzhao1/work/final_RC2rna/annotation/plots/1umap_all_loc.png',res = 300, height = 5600, width = 5200)
p
dev.off()
```


```{r}
feature <- 'G0S2'
df <- data.frame(immune@meta.data)
df$embedding1 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(immune@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(immune, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)

VlnPlot(immune, feature, group.by = 'seurat_clusters_res1.5', pt.size = 0)

```
