#!/bin/bash
sbatch -J colon_only ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/colon_only.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/colon_only ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J colon_core ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/colon_core.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/colon_core ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J ileum_core ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/ileum_core.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/ileum_core ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J ileum_only ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/ileum_only.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/ileum_only ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J pouch2_only ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/pouch2_only.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/pouch2_only ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J pouch2vsAC ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/pouch2vsAC.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/pouch2vsAC ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J pouch2vsAC_excludingTIvsAC ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/pouch2vsAC_excludingTIvsAC.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/pouch2vsAC_excludingTIvsAC ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
sbatch -J ACvspouch2 ~/yuzhao1/work/jobs/run_homer.batch ~/yuzhao1/work/final_RC2atac/peaks/4homer/input/ACvspouch2.bed ~/yuzhao1/work/final_RC2atac/peaks/4homer/output/ACvspouch2 ~/yuzhao1/work/final_RC2atac/peaks/4homer/backgroundPeaks/epithelial.bed
