---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(ArchR)
library(parallel)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ComplexHeatmap)
source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/manu/rc2/scripts/helper_seurat.R')
source('~/yuzhao1/scripts/seurat/deg_pseudobulk.R')
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('~/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
source('~/yuzhao1/work/manu/rc2/scripts/rna_deg_markers.R')
source('~/yuzhao1/scripts/helper_archr.R')
source('~/yuzhao1/work/manu/rc2/scripts/tfs.R')

out.dir <- '/project/gca/yuzhao1/work/final_RC2rna/0revision/reviewer3/1control_ethnicity/plots_heatmap/'
"%&%" <- function(a, b) paste0(a, b)
```

```{r}
seurat_all <- readRDS('~/yuzhao1/work/final_RC2rna/0revision/reviewer3/1control_ethnicity/seurat_ipaa_and_all_controls.rds')
seurat_all$Race[seurat_all$Race == 'More than one Race'] <- 'Unknown'
```

```{r}
seurat <- subset(seurat_all, cells = Cells(seurat_all)[seurat_all$anno1 %in% c('EC1-1', 'EC1-2', "EC2-1", "EC2-2")])
seurat$anno1_loc <- paste0(seurat$anno1, '-', seurat$biopsy_location)
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2") & seurat$biopsy_location =='POU'] <- 'EC-POU1'
seurat$anno1_loc[seurat$anno1 %in% c("EC2-1", "EC2-2") & seurat$biopsy_location =='POU'] <- 'EC-POU2'
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='PP'] <- 'EC-PP'
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='TI'] <- 'EC-TI'
seurat$anno1_loc[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='AC'] <- 'EC-AC'

seurat$anno1_loc <- factor(seurat$anno1_loc, levels = c('EC-AC', 'EC-POU2', 'EC-POU1', 'EC-PP', 'EC-TI'))
seurat <- subset(seurat, cells = Cells(seurat)[seurat$anno1_loc%in%c('EC-AC', 'EC-POU2')])
```


```{r}
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
patients_control <- c("HA02", "HA08", "HA11", "HA50", "HA52", "HA54", "HA01", "HA04", "HA07", "HA49", "HA51", "HA55", "HA62", "OR95")

# Unknown HA01 HA04 HA54
# Black/African-American HA02 HA08 HA11 HA50 HA52
# the others are white
```

### 1, prepare gene sets

```{r}
# to highlight
genes.ec.highlight <- c('OLFM4', 'REG4', 'REG1A', 'DMBT1', 'MUC2', 'LYZ', 'AC138305.1','SERPINB5', 
'SPINK4', 'S100P', 'TFF3', 'PLA2G2A', 'MACROD1', 'NXPE1', 'MYO5C', 
'ANKDD1B', 'CCDC112', 'CASD1', 'LHFPL3', 'TACC1', 'HMGCS2', 
'SELENBP1', 'SATB2', 'NXPE4', 'VSIG2', 'CKB', 'CA12', 'RBFOX1', 'AQP8', 'XACT', 
'MS4A12', 'CEACAM7', 'CA1')
```


```{r}
# get absorptive inflammation and healthy module from smillie data
deg <- read.csv('~/yuzhao1/work/final_RC2rna/inf_analysis/inf_ec_module.csv')
xx <- deg[deg$ident %in% c('E.Absorptive', 'E.Absorptive_All', "E.Immature_Enterocytes", 
                           "Enterocyte Progenitors" ,"Enterocytes", "Immature Enterocytes 1",
                           "Immature Enterocytes 2") & deg$log2fc > 1, ]
genes.smillie_absorptive_upregulated <- unique(xx$gene)

xx <- deg[deg$ident %in% c('E.Absorptive', 'E.Absorptive_All', "E.Immature_Enterocytes", 
                           "Enterocyte Progenitors" ,"Enterocytes", "Immature Enterocytes 1",
                           "Immature Enterocytes 2") & deg$log2fc < -1, ]
genes.smillie_absorptive_downregulated <- unique(xx$gene)
```


```{r}
# EC modules
# get inflammation and healthy module from pouch EC2 vs AC
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_pou2vsAC_bulk.rds')

fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPOU_EC-POU2",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)

df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')

genes_pouch_ec2 <- rownames(df[df$p_val_adj<0.05 & df$logFC > 1, ])
genes_ac_ec <- rownames(df[df$p_val_adj<0.05 & df$logFC < -1, ])

# to help rank by logFC inside each chunk
df_ec_logFC_ref <- df[c(genes_pouch_ec2, genes_ac_ec), ]
```


```{r}
# extra annotation: genes in AC vs TI
markers <- readRDS('~/yuzhao1/work/final_RC2rna/deg/epithelial/ec/markers_filtered_logFC1_p0.05.rds')
temp <- markers[["TIvsAC"]]
refgene_TIvsAC <- rownames(temp)[temp[['logFC']] > 1]
refgene_ACvsTI <- rownames(temp)[temp[['logFC']] < -1]
```



### 2, plot EC

```{r}
# specify the following parameters for a beautiful heatmap

all_smillie_shared <- intersect(c(genes_ac_ec, genes_pouch_ec2),
                                c(genes.smillie_absorptive_upregulated,
                                  genes.smillie_absorptive_downregulated))

genes_to_plot <- intersect(c(all_smillie_shared),
                           all_smillie_shared)

plot_suffix <- '_all'
barwidth1 <- 5
barwidth2 <- 5
plot_font_size <- 8
```

```{r}
# split genes in to 8 blocks by three standard(pouchEC2 vs AC, Smillie, TI vs AC)
df <- as.data.frame(matrix(nrow = length(genes_to_plot),
                           data = 0,
                           ncol = 3))
colnames(df) <- c('pouchEC2vsAC', 'shared', 'TIvsAC')
rownames(df) <- genes_to_plot

# up-regulated in pouch (1) or down-regulated (0)
df[intersect(genes_pouch_ec2, rownames(df)), 'pouchEC2vsAC'] <- 1
df[intersect(genes_ac_ec, rownames(df)), 'pouchEC2vsAC'] <- 2

# smillie inf (1) or non-inf (2)
df[intersect(c(genes.smillie_absorptive_upregulated),
             rownames(df)), 
   'shared'] <- 1

df[intersect(c(genes.smillie_absorptive_downregulated),
             rownames(df)), 
   'shared'] <- 2

# shared with TI vs AC degs
df[intersect(refgene_TIvsAC, rownames(df)), 'TIvsAC'] <- 1 
df[intersect(refgene_ACvsTI, rownames(df)), 'TIvsAC'] <- 2

# logFC in pouchEC2 vs AC
df$pouch2vsAC_logFC <- df_ec_logFC_ref[rownames(df), 'logFC']

# categorize
df$levels <- paste0(df[,1], df[,2], df[,3])

ec.levels = c('111','112','110', # pouch inf + region
              '121','122','120',
           '101','102','100', # pouch other + region
           '211','212','210',
           '221','222','220', # ac healthy + region
           '201','202','200'
           )
ec.levels <- ec.levels[ec.levels %in% unique(df$levels)]

df$levels <- factor(df$levels, levels = ec.levels)
# sort inside each category
df <- df[order(df[,'levels'], -df['pouch2vsAC_logFC']), ]

########################################################################
# seurat
#  EC-POU1-OR43 = 111 cells, EC-POU2-OR43 = 42 cells
seurat$anno1 <- seurat$anno1_loc
seurat$anno1_patient <- paste0(seurat$anno1, '-', seurat$Patient_ID)
seurat$anno1_patient <- factor(seurat$anno1_patient, levels = c(paste0('EC-AC', '-', patients_control),
                                                                paste0('EC-POU2', '-', patients_uc)))
# seurat.sub <- subset(seurat, anno1_patient!='EC-POU2-OR43')
seurat.sub <- seurat

########################################################################
# plot
# the df was prepared in first chunk in this section

Average.expression.mtx <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = rownames(df),
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
Average.expression.mtx <- Average.expression.mtx[rownames(df), 
                                                 c(paste0('EC-AC', '-', patients_control),
                                                   paste0('EC-POU2', '-', patients_uc))]


# filter again to show in labels of heatmap
labels <- c(
  'REG4','DMBT1','SLC6A14','VNN1','TGM2','TFF1','HLA-DRB1','MGAT3','PI3','OLFM4','LPCAT1',
  'UNC5CL','C2','TRIM22','C4BPB','LCN2','MYEOV','CASP1','UNC13D','CFB','TRIM40','SESTD1','KDELR3',
  'LPIN1','ARFGAP3','TMEM92','S100A11', 'ELOVL7','GBP1','FFAR4','ITGA2','XDH','DUSP6','EFNA2','STAT1',
  'MAP3K5','SLC20A1','ZNF703','P2RX4','RNF186','MESP1','MUC4','SELENBP1','OASL','DEFB1','HMGCS2',
  'CA2','AQP8','ANPEP','CASD1','SPINK5','KAZN','SMAD9','HYI','GPX4','TNNC2')


# labels <- genes.show
labels.idx <- match(labels, rownames(Average.expression.mtx))

col2 <- c('0' = '#ffffe5', '1' = '#6a3d9a', '2' = '#fddaec') # shared with smillie inflammed(1), healthy (2)
col3 <- c('0' = '#ffffe5', '1' = '#4292c6', '2' = '#35978f') # region ti (1) ac (2), other (0)
anno1 <- rowAnnotation(
  bar2 = anno_block(gp = gpar(fill = col2[levels(df$levels) %>% substr(., 2, 2)]),
                    width = unit(barwidth1, "mm")),
  bar3 = anno_block(gp = gpar(fill = col3[levels(df$levels) %>% substr(., 3, 3)]),
                    width = unit(barwidth2, "mm")),
  gp = gpar(col = "black")
)
```


```{r}
pdf(paste0(out.dir, 'AA_EC_sample_heatmap', plot_suffix, '.pdf'), width = 7, height = 9)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1,
              cluster_columns = F, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, show_row_names = F,
              row_split = df$levels,
              row_title = NULL,
              row_gap = unit(1, "mm"), 
              column_gap = unit(0, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 2), # element border in each rect chunk
              border_gp = gpar(col = "black", lty = 1, lwd = 1), # chunk border
              
              heatmap_legend_param = list(title = "Mean expression z score"),
              use_raster = F,
              right_annotation = anno1)+
  rowAnnotation(link = anno_mark(at = labels.idx, labels = labels, 
                                 labels_gp = gpar(col = "black", fontsize = plot_font_size)), 
                width = unit(0.1, "cm") + 
                max_text_width(labels))

print(p1)
dev.off()
```



















