---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/umap_colors.R')

union <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/gut_filtered.rds')
epithelial <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
immune <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/immune3.rds')
tcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/tcell2.rds')
bcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/bcell3.rds')
myeloid <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/myeloid3.rds')
others <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/others3.rds')
```

### All cells

```{r}
seurat <- union
```

```{r}
df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$lineage
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_lineage)
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/union_lineage.pdf', width = 4.5, height = 5, pointsize = 1)
p
dev.off()

```

```{r}
df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$lineage
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_lineage)

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/union_lineage_loc.pdf', width = 6, height = 7, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

```

```{r}
df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'number', custom_colors = custom_colors_rna_all, plot_level = names(rna.unionHeatmap.markers))

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/union_anno1_number.pdf', width = 8, height = 10, pointsize = 1)
p
dev.off()

```


```{r}
df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_all)

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/union_anno1_NoName.pdf', width = 8, height = 10, pointsize = 1)
p
dev.off()

```

### immune cells

```{r}
seurat <- immune
```

```{r}
seurat@meta.data$Sample_ID_Corrected <- factor(seurat@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
seurat@meta.data$biopsy_location <- factor(seurat@meta.data$biopsy_location, 
                                           levels = c('TI','PP','POU','AC'))

df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_immune)
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/immune.pdf', width = 6, height = 7, pointsize = 1)
p
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/immune_loc.pdf', width = 6, height = 7, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/immune_sample.pdf', width = 12, height = 10, pointsize = 1)
p +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```



### Epithelial cells

```{r}
seurat <- epithelial
```

```{r}
seurat@meta.data$Sample_ID_Corrected <- factor(seurat@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
seurat@meta.data$biopsy_location <- factor(seurat@meta.data$biopsy_location, 
                                           levels = c('TI','PP','POU','AC'))

df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno2
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_epithelial_anno2,
                       plot_level = names(custom_colors_rna_epithelial_anno2))
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/epithelial.pdf', width = 4.5, height = 5, pointsize = 1)
p
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/epithelial_loc.pdf', width = 6, height = 7, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/epithelial_sample.pdf', width = 12, height = 10, pointsize = 1)
p +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```



### T cells

```{r}
seurat <- tcell
```

```{r}
seurat@meta.data$Sample_ID_Corrected <- factor(seurat@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
seurat@meta.data$biopsy_location <- factor(seurat@meta.data$biopsy_location, 
                                           levels = c('TI','PP','POU','AC'))

df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_tcell)
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/tcell.pdf', width = 4.5, height = 5, pointsize = 1)
p
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/tcell_loc.pdf', width = 6, height = 7, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/tcell_sample.pdf', width = 9, height = 8.2, pointsize = 1)
p +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```



### B cells

```{r}
seurat <- bcell
```

```{r}
seurat@meta.data$Sample_ID_Corrected <- factor(seurat@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
seurat@meta.data$biopsy_location <- factor(seurat@meta.data$biopsy_location, 
                                           levels = c('TI','PP','POU','AC'))

df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_bcell)
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/bcell.pdf', width = 4.5, height = 5, pointsize = 1)
p
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/bcell_loc.pdf', width = 6, height = 7, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/bcell_sample.pdf', width = 9, height = 8.2, pointsize = 1)
p +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```




### Myeloid cells

```{r}
seurat <- myeloid
```

```{r}
seurat@meta.data$Sample_ID_Corrected <- factor(seurat@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
seurat@meta.data$biopsy_location <- factor(seurat@meta.data$biopsy_location, 
                                           levels = c('TI','PP','POU','AC'))

df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_myeloid)
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/myeloid.pdf', width = 4.5, height = 5, pointsize = 1)
p
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/myeloid_loc.pdf', width = 6, height = 7, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/myeloid_sample.pdf', width = 9, height = 8.2, pointsize = 1)
p +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```




### others cells

```{r}
seurat <- others
```

```{r}
seurat@meta.data$Sample_ID_Corrected <- factor(seurat@meta.data$Sample_ID_Corrected,
                                                   levels = c("HA01-TI","HA02-TI","HA04-TI","HA50TI","HA51TI","HA55TI",
                                                              "HA01-AC","HA02-AC","HA04-AC","HA50AC","HA51AC","HA55AC",
                                                              "OR101-PP","OR102-PP","OR109-PP","OR43-PP","OR48-PP","OR72PP",
                                                              "OR101-POU","OR102-POU","OR109-POU","OR43-POU","OR48-POU","OR72POU"
                                                              ))
seurat@meta.data$biopsy_location <- factor(seurat@meta.data$biopsy_location, 
                                           levels = c('TI','PP','POU','AC'))

df <- data.frame(seurat@meta.data)
df$embedding1 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(seurat@reductions$harmony_umap@cell.embeddings)$UMAP_2
df$cluster_name <- seurat$anno1
p<-plot_df_umap_custom(df, show.label = 'na', custom_colors = custom_colors_rna_others, axistitle.textsize = 18, legend.textsize = 8)
p

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/others.pdf', width =7, height = 7.5, pointsize = 1)
p
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/others_loc.pdf', width = 7, height = 8, pointsize = 1)
p +
  facet_wrap( ~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()

pdf('/project/gca/yuzhao1/work/manu/rc2/plots/1rna_umaps/others_sample.pdf', width = 9, height = 8, pointsize = 1)
p +
  facet_wrap(~ Sample_ID_Corrected, ncol = 6) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 6)
  )
dev.off()
```

