---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(ArchR)
library(parallel)
library(BSgenome.Hsapiens.UCSC.hg38)
source('~/yuzhao1/scripts/plot.R')

```

```{r, include = F, eval=F}
source('~/yuzhao1/scripts/helper_archr.R')
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('~/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
source('~/yuzhao1/work/manu/rc2/scripts/rna_deg_markers.R')
```

```{r}
out.dir <- '~/yuzhao1/work/manu/rc2/plots/2rna_degs_volcano/'
```


```{r}
markers <- readRDS('~/yuzhao1/work/final_RC2rna/deg/epithelial/ec/markers_filtered_logFC1_p0.05.rds')
pathways <- readRDS('~/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pathways.rds')
markers.vectors <- list()
names(markers)
```

```{r}
plot.title = "pouch EC2 vs AC"
labeled_genes <- c('REG1A', 'FABP6', 'DMBT1', 'REG4', 'OLFM4', 'TFF3', 'APOA4', 'APOB',
                   'AQP8', 'SLC26A2', 'CA2', 'SLC26A3',  'SPINK4', 'MUC2', 'SATB2',
                   'SLC26A2', 'SELENBP1', 'PI3', 'LYZ',
                   'LCN2', 'HMGCS2', 'HLA-DRA', 'HLA-DRB1', 'FABP1',
                   'DUOXA2', 'CKB', 'CD74',
                   'FOXD2', 'KLF7', 'SOX6')

de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_pou2vsAC_bulk.rds')


fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPOU_EC-POU2",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)

# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold
df$madjp[df$madjp > 300] <- 300

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value)",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
print(p)
dev.off()
```

```{r}
plot.title = "pouch EC1 vs TI"
labeled_genes <- c('REG1A', 'FABP6', 'DMBT1', 'REG4', 'OLFM4', 'TFF3', 
                   'AQP8', 'SLC26A2', 'CA2', 'SLC26A3', 'CA1', 'SPINK4', 'MUC2', 'SATB2',
                   'SLC26A2', 'SELENBP1', 'S100P', 'PLA2G2A', 'PI3', 'LYZ',
                   'LCN2', 'HMGCS2', 'HLA-DRA', 'HLA-DRB1', 'FABP1',
                   'DUOX2', 'DUOXA2', 'CKB', 'CD74')

de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/wilcoxon/')
df <- de_results[, c('avg_log2FC', 'p_val_adj')]
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)

# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold
df$madjp[df$madjp > 300] <- 300

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 20) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value) (capped at 300)",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
p
dev.off()
```

```{r}
plot.title = "PP vs TI"
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_TIvsPP_bulk.rds')


fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subTI_EC-TI",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)


# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold
df$madjp[df$madjp > 300] <- 300

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))


labeled_genes <- sample(rownames(df)[df$Significant == "Significant"], 9)

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value)",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
p
dev.off()
```


```{r}
labeled_genes <- c('REG1A', 'DMBT1', 'SPINK1', 'MUC2', 'OLFM4',  'LCN2',
            'ADH1C', 'SATB2', 'CEACAM7', 'CA2', 'AQP8', 'HES1', 'NXPE4', 'HMGCS2',
            'RPSA', 'CFTR', 'RPL11', 'CEACAM5', 'SOX9', 'MECOM', 'TFCP2L1', 'CD24','FCGBP',
            'SLC7A7', 'GSTA1', 'ACE2', 'RBP2', 'APOA4', 'FABP6', 'HLA−DRA','ABCC2', 'ENPEP',
            'EFNA1', 'SAE1', 'APOA1','APOB', 'SELENOP', 'TRPM6', 
            'SOX6', 'MECOM', 'BACH1', 'CDX2', 'MAF', 'HNF4G'
            )
plot.title = "TIvsAC"
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_EC_TIvsAC.rds')
fclist <- topTable(
  de_results[["EC"]],
  coef = "biopsy_locationTI",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)

# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''
df$label[df$Significant == "Not Significant"] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 1 ) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value)",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
p
dev.off()
```


```{r}
labeled_genes <- c('REG1A', 'DMBT1', 'MUC2', 'OLFM4', 
            'SATB2', 'CEACAM7', 'CA2', 'AQP8', 'HES1',  'HMGCS2',
            'CFTR', 'CEACAM5', 'SOX9', 'MECOM', 'TFCP2L1', 'CD24',
            'SLC7A7', 'GSTA1',  'RBP2', 'APOA4', 'FABP6', 'HLA−DRA','ABCC2', 'ENPEP',
            'EFNA1', 'SAE1', 'TRPM6', 
            'SOX6', 'MECOM', 'BACH1', 'CDX2', 'MAF', 'HNF4G',
            
            "ETS2",   "CA13",   "ABCB1", "PEBP1",   "CDR2",  "KIF2A", "PPARA" 
            )
plot.title = "POU_EC2vsPOU_EC1"
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_POU_EC2vsPOU_EC1.rds')
fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPOU_EC2",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)
df$madjp[df$madjp > 50] <- 50

# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''
df$label[df$Significant == "Not Significant"] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 1 ) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value) (capped at 50)",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
p
dev.off()
```





```{r}
labeled_genes <- c('REG1A', 'DMBT1', 'SPINK1', 'MUC2', 'OLFM4',  'LCN2',
            'ADH1C', 'SATB2', 'CEACAM7', 'CA2', 'AQP8', 'HES1', 'NXPE4', 'HMGCS2',
            'RPSA', 'CFTR', 'RPL11', 'CEACAM5', 'SOX9', 'MECOM', 'TFCP2L1', 'CD24','FCGBP',
            'SLC7A7', 'GSTA1', 'ACE2','APOA4', 'FABP6', 'HLA−DRA','ABCC2', 'ENPEP',
            'EFNA1', 'SAE1', 'APOA1','APOB', 'SELENOP', 'TRPM6', 
            'SOX6', 'MECOM', 'BACH1', 'CDX2', 'MAF', 'HNF4G'
            )
plot.title = "PP_ECvsPOU_EC2"
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_PP_ECvsPOU_EC2.rds')
fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPP_EC-PP",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)

# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''
df$label[df$Significant == "Not Significant"] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 3) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value) ",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
p
dev.off()
```





```{r}
labeled_genes <- c('REG1A', 'DMBT1', 'SPINK1', 'MUC2', 'OLFM4',  'LCN2',
            'ADH1C', 'SATB2', 'CEACAM7', 'CA2', 'AQP8', 'HES1', 'NXPE4', 'HMGCS2',
            'RPSA', 'CFTR', 'RPL11', 'CEACAM5', 'SOX9', 'MECOM', 'TFCP2L1', 'CD24','FCGBP',
            'SLC7A7', 'GSTA1', 'ACE2', 'RBP2', 'APOA4', 'FABP6', 'HLA−DRA','ABCC2', 'ENPEP',
            'EFNA1', 'SAE1', 'APOA1','APOB', 'SELENOP', 'TRPM6', 
            'SOX6', 'MECOM', 'BACH1', 'CDX2', 'MAF', 'HNF4G',
            'ABCC3', 'CAP1', 'DEFA5', 'FOXP2', 'DAPK1', 'FOXP1', 'IRF9',
            'CA4', 'TFF3', 'MUC2', 'SCN9A', 'CHRNA7'
            )
plot.title = "PP_ECvsPOU_EC1"
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_PP_ECvsPOU_EC1.rds')
fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPP_EC-PP",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')
min_nonzero <- min(subset(df$p_val_adj, df$p_val_adj > 0))
df$p_val_adj[df$p_val_adj == 0] <- min_nonzero
colnames(df) <- c('logFC', 'madjp')
df$madjp <- 0-log10(df$madjp)
df$madjp[df$madjp > 20] <- 20

# Set significance thresholds
logFC_threshold <- 1     # Choose a log2 fold change threshold
madjp_threshold <- -log10(0.05)  # Choose an adjusted p-value threshold

# Create a new variable to color significant points
df <- df %>%
  mutate(Significant = ifelse(abs(logFC) > logFC_threshold & madjp > madjp_threshold, "Significant", "Not Significant"))

# Create a new variable for labels
df$label <- rownames(df) 
df$label[!df$label %in% labeled_genes] <- ''
df$label[df$Significant == "Not Significant"] <- ''

p <- ggscatter(df, x = 'logFC', y = 'madjp', color = 'Significant', size = 2) +
  theme_pubr() +
  scale_color_manual(values = c("Not Significant" = "#bdbdbd", "Significant" = "#fd8d3c")) +
  theme(axis.title = element_text(size = 12, face = 'bold'),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        legend.position = "bottom")+
  labs(title="TF regulator",
       x ="Correlation To Gene Expression", y = "Max TF Motif Delta")+
  geom_text_repel(aes(label=label),
                  nudge_y = 0, max.overlaps = 1000, min.segment.length = 0.01,
                  size = 2, force = 3) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = madjp_threshold, linetype = "dashed") +
  geom_vline(xintercept = c(-logFC_threshold, logFC_threshold), linetype = "dashed") +
  guides(color=guide_legend(title=""))+
  labs(title = plot.title,
       x = "Log2 Fold Change",
       y = "-log10(Adjusted P-value) (capped at 20)",
       color = "Significance") +
  theme(legend.position = "bottom")
pdf(paste0(out.dir, plot.title, '.pdf'), width = 5, height = 5)
p
dev.off()
```


















