---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(limma)
library(edgeR)
library(variancePartition)
library(BiocParallel)
# library(tidyverse)
library(ComplexHeatmap)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_deg_markers.R')
source('/project/gca/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
source('/project/gca/yuzhao1/scripts/seurat/deg_pseudobulk.R')
```

```{r, include = F, eval=F}
union <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/gut_filtered.rds')
```

### 1. EC

```{r}
# cci genes
genes <- rna_deg_markers_ec_tfs
plot.title <- 'ec_tfs'

genes <- c('MDK', 'LRP1', 'NR1H4', 'EFNA2', 'EPHA3', 'NR3C1', 'CCL2', 'DPP4', 'CCL11', 'TNFRSF10B', 'TNFSF10',
           'COL17A1', 'CD74', 'MIF', 'CD74', 'COPA', 'APP', 'CXADR', 'FAM3C', 'TNFRSF1A', 'GRN', 'RORA', 'PPARA')
plot.title <- 'cci'

plot.height <- length(genes)*0.25
out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/2rna_deg/EC_heatmap/'
```



```{r}
# dense heatmap for EC only
# all DEGs
genes <- readRDS('~/yuzhao1/work/manu/rc2/plots/2rna_deg/EC_heatmap/genesEC.rds')
# manually filtered DEGs
genes.show <- unique(c(rna_deg_markers_ec_ileum, rna_deg_markers_ec_colon))
tfs <- readRDS('~/yuzhao1/work/manu/rc2/plots/2rna_deg/EC_heatmap/tfsEC.rds')
plot.title <- 'ec_dense'


plot.height <- 10
out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/2rna_deg/EC_heatmap/'
```

```{r}
seurat <- subset(union, cells = Cells(union)[union$anno1 %in% c('EC1-1', 'EC1-2', "EC2-1", "EC2-2")])
seurat$anno1 <- seurat$anno1_loc
seurat$anno1 <- factor(seurat$anno1, levels = c('EC-AC', 'EC-POU2', 'EC-POU1', 'EC-PP', 'EC-TI'))
```


```{r}
seurat$anno1_patient <- paste0(seurat$anno1, '-', seurat$Patient_ID)
patients_control <- grep('HA', unique(seurat$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat$anno1_patient <- factor(seurat$anno1_patient, levels = c(paste0('EC-AC', '-', patients_control),
                                                                paste0('EC-POU2', '-', patients_uc),
                                                                paste0('EC-POU1', '-', patients_uc),
                                                                paste0('EC-PP', '-', patients_uc),
                                                                paste0('EC-TI', '-', patients_control)))
```


```{r}
Average.expression.mtx <- AverageExpression(
  seurat,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
```


```{r, fig.height=15, fig.width=4}
library(ComplexHeatmap)
#group = kmeans((Average.expression.mtx), centers = 6)$cluster

# this scalinf process is only used to identify dendrogram
df <- Average.expression.mtx
df <- scale(df)
d <- dist(df, method = "euclidean")
hc1 <- hclust(d, method = "complete" )
group <- cutree(hc1, k = 5)

# filter again to show in labels of heatmap
labels <- c('REG1A', 'DMBT1', 'SPINK1', 'MUC2', 'OLFM4',
            'ADH1C', 'SATB2', 'CEACAM7', 'CA2', 'AQP8', 'HES1', 'NXPE4', 'HMGCS2',
            'RPSA', 'CFTR', 'RPL11', 'CEACAM5', 'SOX9', 'MECOM', 'TFCP2L1', 'CD24','FCGBP',
            'LCN2',
            'SLC7A7', 'GSTA1', 'ACE2', 'RBP2', 'APOA4', 'FABP6', 'HLA−DRA','ABCC2', 'ENPEP',
            'EFNA1', 'SAE1',
            'APOA1','APOB', 'SELENOP', 'TRPM6'
            )
# labels <- genes.show
labels.idx <- match(labels, rownames(Average.expression.mtx))

pdf(paste0(out.dir, plot.title , '_location.pdf'), width = 5, height = 6)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = F, 
              cluster_rows = cluster_within_group( t(Average.expression.mtx), group),
              show_row_dend = F, show_column_dend = F, show_row_names = F,
              heatmap_legend_param = list(title = "Mean expression z score"),
              use_raster = F)+
  rowAnnotation(link = anno_mark(at = labels.idx, labels = labels, labels_gp = gpar(col = "black", fontsize = 6)), 
                width = unit(0.1, "cm") + 
                max_text_width(labels))

print(p1)
dev.off()
```

```{r}
# prepare this because I removed 2 low-quality samples in sample-wise EC 
seurat.sub <- subset(seurat, anno1_patient!='EC-POU1-OR109' & anno1_patient!='EC-POU2-OR43')
```

```{r}
Average.expression.mtx.patients <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = labels,
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx.patients <- Average.expression.mtx.patients$RNA %>% t(.) %>% scale(.) %>% t(.)
```

```{r, fig.height=12, fig.width=10}
col.split <- c(
  rep('EC-AC', 6),
  rep('EC-POU2', 5),
  rep('EC-POU1', 5),
  rep('EC-PP', 6),
  rep('EC-TI', 6)
)
p2 <- Heatmap(Average.expression.mtx.patients, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = T, cluster_rows = T,
              show_row_dend = F, show_column_dend = F, show_row_names = T,
        rect_gp = gpar(col = "white", lwd = 0.5), cluster_column_slices = FALSE,
        border = F, column_gap = unit(3, "mm"),
        column_split = factor(col.split, levels = c('EC-AC', 'EC-POU2', 'EC-POU1', 'EC-PP', 'EC-TI')),
        use_raster = F
        )

pdf(paste0(out.dir, plot.title , '_sample.pdf'), width = 9, height = 10, pointsize = 1)
print(p2)
dev.off()
```




### 2. Stem

```{r}
features_all <- readRDS('~/yuzhao1/work/final_RC2rna/deg/epithelial/stem/DEGs-Stem_selected.rds')

## 1. non-TF genes
# genes <- features_all %>% unlist() %>% unique() %>% setdiff(., features_all$tfs)
genes <- rna_deg_markers_stem_nonTFs
GroupTested <- 'Stem'
plot.title <- 'Stem_nonTFs'
plot.height <- length(genes)*0.27

## 2. TFs
# genes <- rna_deg_markers_stem_tfs
# GroupTested <- 'Stem'
# plot.title <- 'Stem_tfs'
# plot.height <- length(genes)*0.4

out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/2rna_deg/stem/'
```

```{r}
seurat <- subset(union, cells = Cells(union)[union$anno1 %in% c(GroupTested)])
seurat$anno1 <- paste0(seurat$anno1, '-', seurat$biopsy_location)
seurat$anno1 <- factor(seurat$anno1, levels = paste0(GroupTested, '-', c('AC', 'POU', 'PP', 'TI')))
```

```{r}
seurat$anno1_patient <- paste0(seurat$anno1, '-', seurat$Patient_ID)
patients_control <- grep('HA', unique(seurat$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat$anno1_patient <- factor(seurat$anno1_patient, 
                               levels = c(paste0(GroupTested, '-AC-', patients_control),
                                          paste0(GroupTested, '-POU-', patients_uc),
                                          paste0(GroupTested, '-PP-', patients_uc),
                                          paste0(GroupTested, '-TI-', patients_control)))
```

```{r}
Average.expression.mtx <- AverageExpression(
  seurat,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
```


```{r, fig.height=15, fig.width=4}
pdf(paste0(out.dir, plot.title , '_heatmap_location.pdf'), width = 3.6, height = plot.height)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = F, cluster_rows = T,
              use_raster = F)
print(p1)
dev.off()
```

```{r}
table(seurat$anno1_patient)
seurat.sub <- subset(seurat, anno1_patient!='Stem-POU-OR43')
Average.expression.mtx.patients <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx.patients <- Average.expression.mtx.patients$RNA %>% t(.) %>% scale(.) %>% t(.)
```

```{r, fig.height=12, fig.width=10}
col.split <- c(
  rep(paste0(GroupTested, '-AC'), 6),
  rep(paste0(GroupTested, '-POU'), 5),
  rep(paste0(GroupTested, '-PP'), 6),
  rep(paste0(GroupTested, '-TI'), 6)
)
p2 <- Heatmap(Average.expression.mtx.patients, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = T, cluster_rows = T,
        rect_gp = gpar(col = "white", lwd = 0.5), cluster_column_slices = FALSE,
        border = F, column_gap = unit(3, "mm"),
        column_split = factor(col.split, levels = c(paste0(GroupTested, '-AC'),
                                                    paste0(GroupTested, '-POU'),
                                                    paste0(GroupTested, '-PP'),
                                                    paste0(GroupTested, '-TI'))),
        use_raster = F
        )

pdf(paste0(out.dir, plot.title , '_heatmap_sample.pdf'), width = 9, height = plot.height, pointsize = 1)
print(p2)
dev.off()
```




### 2. Stem2

```{r}
## 1. non-TF genes
genes <- rna_deg_markers_stem_nonTFs
GroupTested <- 'Stem'
plot.title <- 'Stem_nonTFs'
plot.height <- length(genes)*0.27

## 2. TFs
# genes <- rna_deg_markers_stem_tfs
# GroupTested <- 'Stem'
# plot.title <- 'Stem_tfs'
# plot.height <- length(genes)*0.4

out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/2rna_deg/stem2/'

```


```{r}
seurat <- subset(union, cells = Cells(union)[union$anno1 %in% c('Stem')])
seurat$anno1 <- seurat$anno1_loc
seurat$anno1 <- factor(seurat$anno1, levels = c('Stem-AC', 'Stem-POU2', 'Stem-POU1', 'Stem-PP', 'Stem-TI'))
```

```{r}
seurat.sub <- seurat
seurat.sub$anno1_patient <- paste0(seurat.sub$anno1, '-', seurat.sub$Patient_ID)
patients_control <- grep('HA', unique(seurat.sub$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat.sub$anno1_patient <- factor(seurat.sub$anno1_patient, levels = c(paste0('Stem-AC', '-', patients_control),
                                                                        paste0('Stem-POU2', '-', patients_uc),
                                                                        paste0('Stem-POU1', '-', patients_uc),
                                                                        paste0('Stem-PP', '-', patients_uc),
                                                                        paste0('Stem-TI', '-', patients_control)))
```


```{r}
Average.expression.mtx <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
```


```{r, fig.height=15, fig.width=4}
pdf(paste0(out.dir, plot.title , '_location.pdf'), width = 3.6, height = plot.height)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = F, cluster_rows = T,
              use_raster = F)
print(p1)
dev.off()
```

```{r}
table(seurat.sub@meta.data[, c('anno1_loc', 'Sample_ID')])
```


```{r}
LQ_samples <- data.frame(table(seurat.sub$anno1_patient))$Var1[which(data.frame(table(seurat.sub$anno1_patient))$Freq < 30)]
```











### 3. tcell

```{r}
features_all <- readRDS('~/yuzhao1/work/final_RC2rna/deg/tcell/Tcell_nonNK_nonILC/DEGs-tcell_selected.rds')

## 1. non-TF genes
genes <- features_all %>% unlist() %>% unique() %>% setdiff(., features_all$tfs)
# genes <- rna_deg_markers_stem_nonTFs
GroupTested <- 'tcell'
plot.title <- 'tcell'
plot.height <- length(genes)*0.27


out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/2rna_deg/tcell/'
```

```{r}
tcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/tcell2.rds')
seurat <- subset(tcell, anno1 != 'NK' & anno1 != 'ILCs')
seurat$anno1 <- 'tcell'
seurat$anno1 <- paste0(seurat$anno1, '-', seurat$biopsy_location)
seurat$anno1 <- factor(seurat$anno1, levels = paste0(GroupTested, '-', c('AC', 'POU', 'PP', 'TI')))
```

```{r}
seurat$anno1_patient <- paste0(seurat$anno1, '-', seurat$Patient_ID)
patients_control <- grep('HA', unique(seurat$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat$anno1_patient <- factor(seurat$anno1_patient, 
                               levels = c(paste0(GroupTested, '-AC-', patients_control),
                                          paste0(GroupTested, '-POU-', patients_uc),
                                          paste0(GroupTested, '-PP-', patients_uc),
                                          paste0(GroupTested, '-TI-', patients_control)))
```

```{r}
Average.expression.mtx <- AverageExpression(
  seurat,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
```


```{r, fig.height=15, fig.width=4}
pdf(paste0(out.dir, plot.title , '_heatmap_location.pdf'), width = 3.6, height = plot.height)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = F, cluster_rows = T,
              use_raster = F)
print(p1)
dev.off()
```

```{r}
table(seurat$anno1_patient)
seurat.sub <- subset(seurat, anno1_patient!='')
Average.expression.mtx.patients <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx.patients <- Average.expression.mtx.patients$RNA %>% t(.) %>% scale(.) %>% t(.)
```

```{r, fig.height=12, fig.width=10}
col.split <- c(
  rep(paste0(GroupTested, '-AC'), 6),
  rep(paste0(GroupTested, '-POU'), 6),
  rep(paste0(GroupTested, '-PP'), 6),
  rep(paste0(GroupTested, '-TI'), 6)
)
p2 <- Heatmap(Average.expression.mtx.patients, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = T, cluster_rows = T,
        rect_gp = gpar(col = "white", lwd = 0.5), cluster_column_slices = FALSE,
        border = F, column_gap = unit(3, "mm"),
        column_split = factor(col.split, levels = c(paste0(GroupTested, '-AC'),
                                                    paste0(GroupTested, '-POU'),
                                                    paste0(GroupTested, '-PP'),
                                                    paste0(GroupTested, '-TI'))),
        use_raster = F
        )

pdf(paste0(out.dir, plot.title , '_heatmap_sample.pdf'), width = 9, height = plot.height, pointsize = 1)
print(p2)
dev.off()
```




### 4. Goblets

```{r}
features_all <- readRDS('~/yuzhao1/work/final_RC2rna/deg/tcell/Tcell_nonNK_nonILC/DEGs-tcell_selected.rds')

## 1. non-TF genes
genes <- features_all %>% unlist() %>% unique() %>% setdiff(., features_all$tfs)
# genes <- rna_deg_markers_stem_nonTFs
GroupTested <- 'tcell'
plot.title <- 'tcell'
plot.height <- length(genes)*0.27


out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/2rna_deg/tcell/'
```

```{r}
tcell <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/tcell2.rds')
seurat <- subset(tcell, anno1 != 'NK' & anno1 != 'ILCs')
seurat$anno1 <- 'tcell'
seurat$anno1 <- paste0(seurat$anno1, '-', seurat$biopsy_location)
seurat$anno1 <- factor(seurat$anno1, levels = paste0(GroupTested, '-', c('AC', 'POU', 'PP', 'TI')))
```

```{r}
seurat$anno1_patient <- paste0(seurat$anno1, '-', seurat$Patient_ID)
patients_control <- grep('HA', unique(seurat$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat$anno1_patient <- factor(seurat$anno1_patient, 
                               levels = c(paste0(GroupTested, '-AC-', patients_control),
                                          paste0(GroupTested, '-POU-', patients_uc),
                                          paste0(GroupTested, '-PP-', patients_uc),
                                          paste0(GroupTested, '-TI-', patients_control)))
```

```{r}
Average.expression.mtx <- AverageExpression(
  seurat,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
```


```{r, fig.height=15, fig.width=4}
pdf(paste0(out.dir, plot.title , '_heatmap_location.pdf'), width = 3.6, height = plot.height)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = F, cluster_rows = T,
              use_raster = F)
print(p1)
dev.off()
```

```{r}
table(seurat$anno1_patient)
seurat.sub <- subset(seurat, anno1_patient!='')
Average.expression.mtx.patients <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx.patients <- Average.expression.mtx.patients$RNA %>% t(.) %>% scale(.) %>% t(.)
```

```{r, fig.height=12, fig.width=10}
col.split <- c(
  rep(paste0(GroupTested, '-AC'), 6),
  rep(paste0(GroupTested, '-POU'), 6),
  rep(paste0(GroupTested, '-PP'), 6),
  rep(paste0(GroupTested, '-TI'), 6)
)
p2 <- Heatmap(Average.expression.mtx.patients, col = rc2_rna_heatmap_colors_gradient1, cluster_columns = T, cluster_rows = T,
        rect_gp = gpar(col = "white", lwd = 0.5), cluster_column_slices = FALSE,
        border = F, column_gap = unit(3, "mm"),
        column_split = factor(col.split, levels = c(paste0(GroupTested, '-AC'),
                                                    paste0(GroupTested, '-POU'),
                                                    paste0(GroupTested, '-PP'),
                                                    paste0(GroupTested, '-TI'))),
        use_raster = F
        )

pdf(paste0(out.dir, plot.title , '_heatmap_sample.pdf'), width = 9, height = plot.height, pointsize = 1)
print(p2)
dev.off()
```



