---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(ArchR)
library(parallel)
library(BSgenome.Hsapiens.UCSC.hg38)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('~/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
```

```{r, include = F, eval=F}
proj_union <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_filtered/")
proj_epithelial <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_epithelial_filtered2/")
proj_tcell <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_tcell_filtered2/")
proj_bcell <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_bcell_filtered/")
proj_myeloid <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_myeloid_filtered2/")
proj_others <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_others_filtered2/")
```

```{r}
out.dir <- '~/yuzhao1/work/manu/rc2/plots/4atac_MarkerTFs/'
```

### 1. epithelial

```{r}
lineage <- 'epithelial'
proj <- proj_epithelial
```


```{r}
df <- readRDS(paste0(proj@projectMetadata$outputDirectory, '/', 'MarkersPeaks_anno2_epithelial_enriched_mlog10Padj_filtered', '.rds'))


rownames(df) <- df$tf

df$tf_full <- NULL
df$tf <- NULL
df <- t(df)

############### cap at cap and scale  #################
cap <- 100
for (i in 1:nrow(df)) {
  for(j in 1:ncol(df)){
    df[i,j] <- ifelse(df[i,j]>cap, cap, df[i,j])
  }
}
# apply a function to each row to scale it to a range of 0 to 100
scaled_0_to_100 <- sapply(1:nrow(df), function(i) {
  rescaled_row <- (df[i,] - min(df[i,])) / (max(df[i,]) - min(df[i,])+0.0000001) * 100
  return(rescaled_row)
})

# convert the resulting matrix back to a dataframe
scaled_df_0_to_100 <- data.frame(t(scaled_0_to_100))

# make sure this is the order same with marker peaks
rownames(scaled_df_0_to_100) <- rownames(df)
df <-scaled_df_0_to_100[rownames(df), ]

pal <- c('#fcfbfd','#efedf5','#bcbddc','#9e9ac8','#807dba','#6a51a3','#54278f','#3f007d')
col_fun <- colorRamp2(seq(0, cap, cap/(length(pal)-1)), pal)
                      
############### end capping and scaling  #################

df <- df[names(custom_colors_atac_epithelial_anno2), ]

pdf(paste0(out.dir, lineage, '.pdf'), width = 10, height =3)
p1 <- Heatmap(df, 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = T, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()

pdf(paste0(out.dir, lineage, '_t.pdf'), width = 6, height =10)
p1 <- Heatmap(t(df), 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = F, cluster_rows = T,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()
```


### 2. tcell

```{r}
lineage <- 'tcell'
proj <- proj_tcell
```


```{r}
df <- readRDS(paste0(proj@projectMetadata$outputDirectory, '/', 'MarkersPeaks_anno1_enriched_mlog10Padj_filtered', '.rds'))
rownames(df) <- df$tf

df$tf_full <- NULL
df$tf <- NULL
df <- t(df)

############### cap at cap and scale  #################
cap <- 50
for (i in 1:nrow(df)) {
  for(j in 1:ncol(df)){
    df[i,j] <- ifelse(df[i,j]>cap, cap, df[i,j])
  }
}
# apply a function to each row to scale it to a range of 0 to 100
scaled_0_to_100 <- sapply(1:nrow(df), function(i) {
  rescaled_row <- (df[i,] - min(df[i,])) / (max(df[i,]) - min(df[i,])+0.0000001) * 100
  return(rescaled_row)
})

# convert the resulting matrix back to a dataframe
scaled_df_0_to_100 <- data.frame(t(scaled_0_to_100))

# make sure this is the order same with marker peaks
rownames(scaled_df_0_to_100) <- rownames(df)
df <-scaled_df_0_to_100[rownames(df), ]

pal <- c('#fcfbfd','#efedf5','#bcbddc','#9e9ac8','#807dba','#6a51a3','#54278f','#3f007d')
col_fun <- colorRamp2(seq(0, cap, cap/(length(pal)-1)), pal)
                      
############### end capping and scaling  #################
df <- df[names(custom_colors_atac_tcell), ]

pdf(paste0(out.dir, lineage, '.pdf'), width = 10, height =3)
p1 <- Heatmap(df, 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = T, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()

pdf(paste0(out.dir, lineage, '_t.pdf'), width = 5.5, height =7)
p1 <- Heatmap(t(df), 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = F, cluster_rows = T,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()
```





### 3. bcell

```{r}
lineage <- 'bcell'
proj <- proj_bcell
```


```{r}
df <- readRDS(paste0(proj@projectMetadata$outputDirectory, '/', 'MarkersPeaks_anno1_enriched_mlog10Padj_filtered', '.rds'))
rownames(df) <- df$tf

df$tf_full <- NULL
df$tf <- NULL
df <- t(df)

############### cap at cap and scale  #################
cap <- 50
for (i in 1:nrow(df)) {
  for(j in 1:ncol(df)){
    df[i,j] <- ifelse(df[i,j]>cap, cap, df[i,j])
  }
}
# apply a function to each row to scale it to a range of 0 to 100
scaled_0_to_100 <- sapply(1:nrow(df), function(i) {
  rescaled_row <- (df[i,] - min(df[i,])) / (max(df[i,]) - min(df[i,])+0.0000001) * 100
  return(rescaled_row)
})

# convert the resulting matrix back to a dataframe
scaled_df_0_to_100 <- data.frame(t(scaled_0_to_100))

# make sure this is the order same with marker peaks
rownames(scaled_df_0_to_100) <- rownames(df)
df <-scaled_df_0_to_100[rownames(df), ]

pal <- c('#fcfbfd','#efedf5','#bcbddc','#9e9ac8','#807dba','#6a51a3','#54278f','#3f007d')
col_fun <- colorRamp2(seq(0, cap, cap/(length(pal)-1)), pal)
                      
############### end capping and scaling  #################

df <- df[names(custom_colors_atac_bcell), ]

pdf(paste0(out.dir, lineage, '.pdf'), width = 10, height =3)
p1 <- Heatmap(df, 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = T, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()

pdf(paste0(out.dir, lineage, '_t.pdf'), width = 4.2, height =7)
p1 <- Heatmap(t(df), 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = F, cluster_rows = T,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()
```





### 4. myeloid

```{r}
lineage <- 'myeloid'
proj <- proj_myeloid
```


```{r}
df <- readRDS(paste0(proj@projectMetadata$outputDirectory, '/', 'MarkersPeaks_anno1_enriched_mlog10Padj_filtered', '.rds'))
rownames(df) <- df$tf

df$tf_full <- NULL
df$tf <- NULL
df <- t(df)

############### cap at cap and scale  #################
cap <- 50
for (i in 1:nrow(df)) {
  for(j in 1:ncol(df)){
    df[i,j] <- ifelse(df[i,j]>cap, cap, df[i,j])
  }
}
# apply a function to each row to scale it to a range of 0 to 100
scaled_0_to_100 <- sapply(1:nrow(df), function(i) {
  rescaled_row <- (df[i,] - min(df[i,])) / (max(df[i,]) - min(df[i,])+0.0000001) * 100
  return(rescaled_row)
})

# convert the resulting matrix back to a dataframe
scaled_df_0_to_100 <- data.frame(t(scaled_0_to_100))

# make sure this is the order same with marker peaks
rownames(scaled_df_0_to_100) <- rownames(df)
df <-scaled_df_0_to_100[rownames(df), ]

pal <- c('#fcfbfd','#efedf5','#bcbddc','#9e9ac8','#807dba','#6a51a3','#54278f','#3f007d')
col_fun <- colorRamp2(seq(0, cap, cap/(length(pal)-1)), pal)
                      
############### end capping and scaling  #################

df <- df[names(custom_colors_atac_myeloid), ]
                      
pdf(paste0(out.dir, lineage, '.pdf'), width = 10, height =3)
p1 <- Heatmap(df, 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = T, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()

pdf(paste0(out.dir, lineage, '_t.pdf'), width = 4.5, height =6.5)
p1 <- Heatmap(t(df), 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = F, cluster_rows = T,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()
```







### 5. stromal

```{r}
lineage <- 'stromal'
proj <- proj_others
```


```{r}
df <- readRDS(paste0(proj@projectMetadata$outputDirectory, '/', 'MarkersPeaks_anno1_enriched_mlog10Padj_filtered', '.rds'))
rownames(df) <- df$tf

df$tf_full <- NULL
df$tf <- NULL
df <- t(df)

############### cap at cap and scale  #################
cap <- 50
for (i in 1:nrow(df)) {
  for(j in 1:ncol(df)){
    df[i,j] <- ifelse(df[i,j]>cap, cap, df[i,j])
  }
}
# apply a function to each row to scale it to a range of 0 to 100
scaled_0_to_100 <- sapply(1:nrow(df), function(i) {
  rescaled_row <- (df[i,] - min(df[i,])) / (max(df[i,]) - min(df[i,])+0.0000001) * 100
  return(rescaled_row)
})

# convert the resulting matrix back to a dataframe
scaled_df_0_to_100 <- data.frame(t(scaled_0_to_100))

# make sure this is the order same with marker peaks
rownames(scaled_df_0_to_100) <- rownames(df)
df <-scaled_df_0_to_100[rownames(df), ]

pal <- c('#fcfbfd','#efedf5','#bcbddc','#9e9ac8','#807dba','#6a51a3','#54278f','#3f007d')
col_fun <- colorRamp2(seq(0, cap, cap/(length(pal)-1)), pal)
                      
############### end capping and scaling  #################

df <- df[names(custom_colors_atac_others), ]
pdf(paste0(out.dir, lineage, '.pdf'), width = 10, height =3)
p1 <- Heatmap(df, 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = T, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()

pdf(paste0(out.dir, lineage, '_t.pdf'), width = 5.1, height =5)
p1 <- Heatmap(t(df), 
              col = col_fun,
              
              row_names_gp = gpar(fontsize = 8),
              column_names_gp = gpar(fontsize = 8),
              
              # column_split = factor(c(rep('Enriched in TI', 16), c(rep('Enriched in AC', 15))),
              #                    levels = c('Enriched in TI', 'Enriched in AC')),
              column_gap = unit(12, "mm"), 
              border = T,
              rect_gp = gpar(col = "white", lwd = 1), 

              
              cluster_columns = F, cluster_rows = T,
              show_row_dend = F, show_column_dend = F, 
              show_column_names = T,
              show_row_names = T,
              heatmap_legend_param = list(title = "enrichment: -log10(adjusted p value)"),
              use_raster = F)

print(p1)
dev.off()
```

















