---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(ArchR)

source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('~/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
out.dir <- '~/yuzhao1/work/manu/rc2/plots/4atac_annotation_UnionHeatmap/'
```


```{r, include = F, eval=F}
proj_union <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_filtered/")
gsm_imputated <- readRDS('~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_filtered/GeneScoreMatrix_imputed.rds')
```




###################### 1. Annotation dot plot ########################

```{r}
# markers <- readRDS('~/yuzhao1/work/manu/rc2/plots/1rna_annotation_UnionHeatmap/markers.rds')
top10 <- readRDS('~/yuzhao1/work/manu/rc2/plots/1rna_annotation_UnionHeatmap/top10.rds')
```


### make complex heatmap



```{r}
# beucase the atac union marker are edited based on same order with rna data
# just do an intersection to those genes shared in atac data, keep rna orders
# then plot average expression based on correct order of clusters (saved in names(atac.unionHeatmap.markers))

anno1.order <- names(rna.unionHeatmap.markers)
top10_combined <- do.call(rbind, top10)
genes <- list()
for (anno1 in anno1.order) {
  genes[[anno1]] <- top10_combined$gene[which(top10_combined$cluster==anno1)]
}

genes[["Stem"]] <- c('EPCAM', genes[["Stem"]])
genes[['TA']] <- c(genes[['TA']], 'MKI67')
genes[['Goblet2']] <- c(genes[['Goblet2']], 'BEST2')
genes[['CD4 Tcm']] <- c('CD3D', genes[['CD4 Tcm']], 'TCF7')
genes[['Treg']] <- c(genes[['Treg']], 'FOXP3')
genes[["CD103- CD4 Trm"]] <- c(genes[["CD103- CD4 Trm"]], 'ITGAE')
genes[["KLRG1+ CD4 Trm"]] <- c(genes[["KLRG1+ CD4 Trm"]], 'KLRG1')
genes[["GC B"]] <- c('CD79A', genes[["GC B"]], 'BCL6')
genes[["Naive B"]] <- c(genes[["Naive B"]], 'IGHD')
genes[["Memory B"]] <- c(genes[["Memory B"]], 'CD27')
genes[["Macrophage"]] <- c(genes[["Macrophage"]], 'CD14')
genes[["cDC1"]] <- c(genes[["cDC1"]], 'CLEC9A')
genes[["Stromal-1"]] <- c('IGFBP7', genes[["Stromal-1"]])

genes <- genes[anno1.order]
genes <- unique(genes %>% unlist())

genes <- intersect(genes, rownames(gsm_imputated))
```


```{r}
seurat <- CreateSeuratObject(counts = gsm_imputated[genes,],
                             meta.data = as.data.frame(proj_union@cellColData))
```

```{r}
Average.expression.mtx <- AverageExpression(
  seurat,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
Average.expression.mtx <- Average.expression.mtx[genes, names(atac.unionHeatmap.markers)] # make sure the matrix is in desired order
```


```{r, fig.height=15, fig.width=4}
library(ComplexHeatmap)
library(RColorBrewer)
# show some labels in labels of heatmap
labels <- atac.unionHeatmap.markers %>% unlist() %>% intersect(., rownames(gsm_imputated))
labels.idx <- match(labels, rownames(Average.expression.mtx))

length(manual_colors_gradient3)
# col_fun = colorRamp2(seq(-2, 9, by = 11/9), manual_colors_gradient3)
col_fun = colorRamp2(seq(-2, 6, by = 8/10), rc2_rna_heatmap_colors_gradient1[2:12])
# col_fun = colorRamp2(seq(-2, 8, by = 10/13), c(rep('white', 4), manual_colors_gradient3))

virdis_option <- "turbo"
pdf(paste0(out.dir, virdis_option, '_union.pdf'), width = 8, height = 8)
p1 <- Heatmap(Average.expression.mtx, 
              column_split = factor(c(rep('epithelial', 11),
                                    rep('tcell', 10),
                                    rep('bcell', 4),
                                    rep('myeloid', 5),
                                    rep('others', 9)),
              levels = c('epithelial', 'tcell', 'bcell', 'myeloid', 'others')),
              column_title = NULL,
              row_gap = unit(0, "mm"), column_gap = unit(0, "mm"), 
              border = T,
              border_gp = gpar(col = "black", lty = 1, lwd = 1),
              
              col = viridis_pal(option = virdis_option)(10), 
              cluster_columns = F, show_column_dend = F,
              column_names_gp = gpar(fontsize = 8),
              cluster_rows = F, show_row_dend = F, 
              show_row_names = F,
              heatmap_legend_param = list(title = "Mean expression z score"),
              use_raster = F)+
  rowAnnotation(link = anno_mark(at = labels.idx, labels = labels, labels_gp = gpar(col = "black", fontsize = 6)), 
                width = unit(0.1, "cm") + 
                max_text_width(labels))

print(p1)
dev.off()
```








