---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(ArchR)
library(parallel)
library(BSgenome.Hsapiens.UCSC.hg38)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('~/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
```

```{r, include = F, eval=F}
proj_union <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_filtered/")
proj_epithelial <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_epithelial_filtered2/")
proj_tcell <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_tcell_filtered2/")
proj_bcell <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_bcell_filtered/")
proj_myeloid <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_myeloid_filtered2/")
proj_others <- loadArchRProject(path = "~/yuzhao1/work/final_RC2atac/dataset/gut_2kmin_6TSS_DoubletRatio2_others_filtered2/")
```

```{r}
out.dir <- '~/yuzhao1/work/manu/rc2/plots/4atac_MarkerTracks/'
```

### bed files for UCSC tracks

```{r}
source('~/yuzhao1/work/manu/rc2/scripts/marker_regions.r')
temp_lineage <- 'myeloid'

marker_regions <- paste0('marker_regions_', temp_lineage) %>% as.name(.) %>% eval(.)
marker_region_seqs <- marker_regions %>% strsplit(., '\n') %>% unlist() %>% strsplit(., ' ') %>% sapply(.,`[[`,1)
marker_region_lef <- marker_regions %>% strsplit(., '\n') %>% unlist() %>% strsplit(., ' ') %>% sapply(.,`[[`,2) %>% as.numeric()
marker_region_right <- marker_regions %>% strsplit(., '\n') %>% unlist() %>% strsplit(., ' ') %>% sapply(.,`[[`,3) %>% as.numeric()
marker_region_centers <- floor((marker_region_lef + marker_region_right)/2)
```

```{r}
out_data <- cbind(marker_region_seqs,
                  marker_region_centers - 1000,
                  marker_region_centers + 1000)
write.table(out_data,file=paste0(out.dir, "markerRegions_", temp_lineage, ".bed"),quote=F,row.names=F,col.names=F,sep="\t")
```































