---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(ArchR)
library(parallel)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ComplexHeatmap)
source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/manu/rc2/scripts/helper_seurat.R')
source('~/yuzhao1/scripts/seurat/deg_pseudobulk.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('~/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
source('~/yuzhao1/work/manu/rc2/scripts/rna_deg_markers.R')
source('~/yuzhao1/scripts/helper_archr.R')
source('~/yuzhao1/work/manu/rc2/scripts/tfs.R')
```

```{r, include = F, eval=F}
union <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/gut_filtered.rds')
seurat <- subset(union, cells = Cells(union)[union$anno1 %in% c('EC1-1', 'EC1-2', "EC2-1", "EC2-2")])
seurat$anno1_loc <- factor(seurat$anno1_loc, levels = c('EC-AC', 'EC-POU2', 'EC-POU1', 'EC-PP', 'EC-TI'))

seurat2 <- subset(union, cells = Cells(union)[union$anno1 %in% c('Goblet1', 'Goblet2')])
seurat2$anno1[seurat2$anno1 %in% c("Goblet1") & seurat2$biopsy_location =='POU'] <- 'Goblet-POU1'
seurat2$anno1[seurat2$anno1 %in% c("Goblet2") & seurat2$biopsy_location =='POU'] <- 'Goblet-POU2'
seurat2$anno1[seurat2$anno1 %in% c("Goblet1", "Goblet2") & seurat2$biopsy_location =='PP'] <- 'Goblet-PP'
seurat2$anno1[seurat2$anno1 %in% c("Goblet1", "Goblet2") & seurat2$biopsy_location =='TI'] <- 'Goblet-TI'
seurat2$anno1[seurat2$anno1 %in% c("Goblet1", "Goblet2") & seurat2$biopsy_location =='AC'] <- 'Goblet-AC'

out.dir <- '~/yuzhao1/work/manu/rc2/plots/8inflamed_gene_dense/'
```


### 1, prepare gene sets

```{r}
# to highlight
genes.ec.highlight <- c('OLFM4', 'REG4', 'REG1A', 'DMBT1', 'MUC2', 'LYZ', 'AC138305.1','SERPINB5', 
'SPINK4', 'S100P', 'TFF3', 'PLA2G2A', 'MACROD1', 'NXPE1', 'MYO5C', 
'ANKDD1B', 'CCDC112', 'CASD1', 'LHFPL3', 'TACC1', 'HMGCS2', 
'SELENBP1', 'SATB2', 'NXPE4', 'VSIG2', 'CKB', 'CA12', 'RBFOX1', 'AQP8', 'XACT', 
'MS4A12', 'CEACAM7', 'CA1')

genes.gb.highlight <- c('LYZ', 'OLFM4', 'DMBT1', 'REG1A', 'HSPA5', 'CALR', 'HSP90B1', 'SDF2L1', 'PDIA4',
'S100P', 'FKBP11', 'S100A16', 'SEC11C', 'HMGCS2', 'IQCM', 'CAMK1D', 'EDIL3', 'VSIG2', 'XACT', 'CNTN4', 'RBFOX1', 'C10orf99', 'SETBP1', 'EFNA5', 'PPM1L', 'SEMA5A', 'PDIA3', 'CKB', 'B4GALNT2',
'AC019330.1', 'LHFPL3', 'FOXO1')
```


```{r}
# get absorptive inflammation and healthy module from smillie data
deg <- read.csv('~/yuzhao1/work/final_RC2rna/inf_analysis/inf_ec_module.csv')
xx <- deg[deg$ident %in% c('E.Absorptive', 'E.Absorptive_All', "E.Immature_Enterocytes", 
                           "Enterocyte Progenitors" ,"Enterocytes", "Immature Enterocytes 1",
                           "Immature Enterocytes 2") & deg$log2fc > 1, ]
genes.smillie_absorptive_upregulated <- unique(xx$gene)

xx <- deg[deg$ident %in% c('E.Absorptive', 'E.Absorptive_All', "E.Immature_Enterocytes", 
                           "Enterocyte Progenitors" ,"Enterocytes", "Immature Enterocytes 1",
                           "Immature Enterocytes 2") & deg$log2fc < -1, ]
genes.smillie_absorptive_downregulated <- unique(xx$gene)
```

```{r}
# get secretory inflammation and healthy module from smillie data
deg <- read.csv('~/yuzhao1/work/final_RC2rna/inf_analysis/inf_ec_module.csv')
xx <- deg[deg$ident %in% c('E.Secretory', "E.Secretory_All", "Goblet", "Immature Goblet") & deg$log2fc > 1, ]
genes.smillie_secretory_upregulated <- unique(xx$gene)

xx <- deg[deg$ident %in% c('E.Secretory', "E.Secretory_All", "Goblet", "Immature Goblet") & deg$log2fc < -1, ]
genes.smillie_secretory_downregulated <- unique(xx$gene)
```

```{r}
# EC modules
# get inflammation and healthy module from pouch EC2 vs AC
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_pou2vsAC_bulk.rds')

fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPOU_EC-POU2",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)

df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')

genes_pouch_ec2 <- rownames(df[df$p_val_adj<0.05 & df$logFC > 1, ])
genes_ac_ec <- rownames(df[df$p_val_adj<0.05 & df$logFC < -1, ])

# to help rank by logFC inside each chunk
df_ec_logFC_ref <- df[c(genes_pouch_ec2, genes_ac_ec), ]
```


```{r}
# Goblet modules
# get inflammation and healthy module from pouch EC2 vs AC
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/goblet/de_results_pou2vsAC_bulk.rds')
fclist <- topTable(
  de_results[["Goblet"]],
  coef = "anno1.subPOU_Goblet-POU2",
  p.value = 1000000,
  sort.by = 'logFC',
  number = 30000
)
df <- fclist[, c('logFC', 'adj.P.Val')]
colnames(df) <- c('logFC', 'p_val_adj')

genes_pouch_goblet2 <- rownames(df[df$p_val_adj<0.05 & df$logFC > 1, ])
genes_ac_goblet <- rownames(df[df$p_val_adj<0.05 & df$logFC < -1, ])

# to help rank by logFC inside each chunk
df_goblet_logFC_ref <- df[c(genes_pouch_ec2, genes_ac_ec), ]
```

```{r}
# extra annotation: genes in AC vs TI
markers <- readRDS('~/yuzhao1/work/final_RC2rna/deg/epithelial/ec/markers_filtered_logFC1_p0.05.rds')
temp <- markers[["TIvsAC"]]
refgene_TIvsAC <- rownames(temp)[temp[['logFC']] > 1]
refgene_ACvsTI <- rownames(temp)[temp[['logFC']] < -1]

# precomputed in ~/yuzhao1/work/final_RC2rna/deg/5Goblet: AAsummary.Rmd
genes.goblet <- readRDS('~/yuzhao1/work/manu/rc2/plots/2rna_deg/goblet/genes_goblet.rds') 
refgene_TIvsAC_goblet <- genes.goblet$TIvsAC
refgene_ACvsTI_goblet <- genes.goblet$ACvsTI
```

### 2, summarize gene sets

```{r}
# # 1, EC
# genes_pouch_ec2_shared <- intersect(genes_pouch_ec2, genes.smillie_absorptive_upregulated)
# 
# genes_pouch_ec2_unique <- setdiff(genes_pouch_ec2, genes.smillie_absorptive_upregulated)
# 
# genes_ac_ec_shared <- intersect(genes_ac_ec, genes.smillie_absorptive_downregulated)
# 
# genes_ac_ec_unique <- setdiff(genes_ac_ec, genes.smillie_absorptive_downregulated)
```

```{r}
# # 2, Goblet
# genes_pouch_goblet2_shared <- intersect(genes_pouch_goblet2, genes.smillie_secretory_upregulated)
# 
# genes_pouch_goblet2_unique <- setdiff(genes_pouch_goblet2, genes.smillie_secretory_upregulated)
# 
# genes_ac_goblet_shared <- intersect(genes_ac_goblet, genes.smillie_secretory_downregulated)
# 
# genes_ac_goblet_unique <- setdiff(genes_ac_goblet, genes.smillie_secretory_downregulated)

```


### 3, plot EC

```{r}
# split genes in to 8 blocks by three standard(pouchEC2 vs AC, Smillie, TI vs AC)
df <- as.data.frame(matrix(nrow = length(c(genes_pouch_ec2, genes_ac_ec)),
                           data = 0,
                           ncol = 3))
colnames(df) <- c('pouchEC2vsAC', 'shared', 'TIvsAC')
rownames(df) <- c(genes_pouch_ec2, genes_ac_ec)

# up-regulated in pouch (1) or down-regulated (0)
df[genes_pouch_ec2, 'pouchEC2vsAC'] <- 1
df[genes_ac_ec, 'pouchEC2vsAC'] <- 2

# smillie inf (1) or non-inf (2)
df[intersect(c(genes.smillie_absorptive_upregulated),
             rownames(df)), 
   'shared'] <- 1

df[intersect(c(genes.smillie_absorptive_downregulated),
             rownames(df)), 
   'shared'] <- 2

# shared with TI vs AC degs
df[intersect(refgene_TIvsAC, rownames(df)), 'TIvsAC'] <- 1 
df[intersect(refgene_ACvsTI, rownames(df)), 'TIvsAC'] <- 2

# logFC in pouchEC2 vs AC
df$pouch2vsAC_logFC <- df_ec_logFC_ref[rownames(df), 'logFC']

# categorize
df$levels <- paste0(df[,1], df[,2], df[,3])

ec.levels = c('111','112','110', # pouch inf + region
              '121','122','120',
           '101','102','100', # pouch other + region
           '211','212','210',
           '221','222','220', # ac healthy + region
           '201','202','200'
           )
ec.levels <- ec.levels[ec.levels %in% unique(df$levels)]

df$levels <- factor(df$levels, levels = ec.levels)
# sort inside each category
df <- df[order(df[,'levels'], -df['pouch2vsAC_logFC']), ]

```


```{r}
#  EC-POU1-OR43 = 111 cells, EC-POU2-OR43 = 42 cells
seurat$anno1 <- seurat$anno1_loc
seurat <- subset(seurat, cells = Cells(seurat)[seurat$anno1_loc%in%c('EC-AC', 'EC-POU2')])
seurat$anno1_patient <- paste0(seurat$anno1, '-', seurat$Patient_ID)
patients_control <- grep('HA', unique(seurat$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat$anno1_patient <- factor(seurat$anno1_patient, levels = c(paste0('EC-AC', '-', patients_control),
                                                                paste0('EC-POU2', '-', patients_uc)))
# seurat.sub <- subset(seurat, anno1_patient!='EC-POU2-OR43')
seurat.sub <- seurat
```

```{r}
# the df was prepared in first chunk in this section
genes_all <- rownames(df)

Average.expression.mtx <- AverageExpression(
  seurat.sub,
  assays = 'RNA',
  features = genes_all,
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
Average.expression.mtx <- Average.expression.mtx[, c('EC-AC-HA01', 'EC-AC-HA02', 'EC-AC-HA04',
                                                     'EC-AC-HA50', 'EC-AC-HA51', 'EC-AC-HA55', 
                                                     'EC-POU2-OR48', 'EC-POU2-OR101',  'EC-POU2-OR102',
                                                     'EC-POU2-OR109', 'EC-POU2-OR43', 'EC-POU2-OR72')]



col1 <- c('1' = 'red', '2' = 'green') # pouch ec2 (1) vs ac ec(2)
col2 <- c('0' = '#ffffe5', '1' = '#6a3d9a', '2' = '#fddaec') # shared with smillie inflammed(1), healthy (2)
col3 <- c('0' = '#ffffe5', '1' = '#4292c6', '2' = '#35978f') # region ti (1) ac (2), other (0)
anno1 <- rowAnnotation(
  # bar1 = anno_block(gp = gpar(fill = col1[levels(df$levels) %>% substr(., 1, 1)]),
  #                   width = unit(3, "mm")),
  bar2 = anno_block(gp = gpar(fill = col2[levels(df$levels) %>% substr(., 2, 2)]),
                    width = unit(3, "mm")),
  bar3 = anno_block(gp = gpar(fill = col3[levels(df$levels) %>% substr(., 3, 3)]),
                    width = unit(3, "mm")),
  gp = gpar(col = "black")
)



pdf(paste0(out.dir, 'EC_sample_heatmap_dense2.pdf'), width = 4.5, height = 8)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1,
              cluster_columns = F, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, show_row_names = F,
              row_split = df$levels,
              row_title = NULL,
              row_gap = unit(1, "mm"), column_gap = unit(0, "mm"), 
              border = T,
              border_gp = gpar(col = "black", lty = 1, lwd = 0),
              
              heatmap_legend_param = list(title = "Mean expression z score"),
              use_raster = F,
              right_annotation = anno1)


print(p1)
dev.off()

# please manually do it in AI: 45   9  27 386  49 254   3  15  11  21 353 269 
```


### heatmap GB
```{r}
seurat2 <- subset(seurat2, cells = Cells(seurat2)[seurat2$anno1%in%c('Goblet-AC', 'Goblet-POU2')])
seurat2$anno1_patient <- paste0(seurat2$anno1, '-', seurat2$Patient_ID)
patients_control <- grep('HA', unique(seurat2$Patient_ID), value = T)
patients_uc <- c("OR109",  "OR48",  "OR102", "OR101", "OR43",  "OR72")
seurat2$anno1_patient <- factor(seurat2$anno1_patient, 
                                levels = c(paste0('Goblet-AC', '-', patients_control),
                                           paste0('Goblet-POU2', '-', patients_uc)))
seurat2.sub <- seurat2
```

```{r}
# split genes in to 8 blocks by three standard(pouchEC2 vs AC, Smillie, TI vs AC)
df <- as.data.frame(matrix(nrow = length(c(genes_pouch_goblet2, genes_ac_goblet)),
                           data = 0,
                           ncol = 3))
colnames(df) <- c('pouchGoblet2vsAC', 'shared', 'TIvsAC')
rownames(df) <- c(genes_pouch_goblet2, genes_ac_goblet)

# up-regulated in pouch (1) or down-regulated (0)
df[genes_pouch_goblet2, 'pouchGoblet2vsAC'] <- 1
df[genes_ac_goblet, 'pouchGoblet2vsAC'] <- 2

# pouch shared with inf (1) or ac shared with non-inf (2)
df[intersect(c(genes.smillie_secretory_upregulated),
             rownames(df)), 
   'shared'] <- 1

df[intersect(c(genes.smillie_secretory_downregulated),
             rownames(df)), 
   'shared'] <- 2

# shared with TI vs AC degs
df[intersect(refgene_TIvsAC_goblet, rownames(df)), 'TIvsAC'] <- 1 
df[intersect(refgene_ACvsTI_goblet, rownames(df)), 'TIvsAC'] <- 2

# logFC in pouchEC2 vs AC
df$pouch2vsAC_logFC <- df_goblet_logFC_ref[rownames(df), 'logFC']

# categorize
df$levels <- paste0(df[,1], df[,2], df[,3])

# some levels are not existing in goblet case, do a sorted intersection
gb.levels = c('111','112','110', # pouch inf + region
              '121','122','120',
           '101','102','100', # pouch other + region
           '211','212','210',
           '221','222','220', # ac healthy + region
           '201','202','200'
           )
gb.levels <- gb.levels[gb.levels %in% unique(df$levels)]

df$levels <- factor(df$levels, levels = gb.levels) 
# sort inside each category
df <- df[order(df[,'levels'], -df['pouch2vsAC_logFC']), ]

```

```{r, fig.height=15, fig.width=4}
# dense heatmap
genes_all <- rownames(df)

Average.expression.mtx <- AverageExpression(
  seurat2.sub,
  assays = 'RNA',
  features = genes_all,
  return.seurat = FALSE,
  group.by = "anno1_patient",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <-
  Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
Average.expression.mtx <-
  Average.expression.mtx[, c(
    'Goblet-AC-HA01',
    'Goblet-AC-HA02',
    'Goblet-AC-HA04',
    'Goblet-AC-HA50',
    'Goblet-AC-HA51',
    'Goblet-AC-HA55',
    'Goblet-POU2-OR48',
    'Goblet-POU2-OR101',
    'Goblet-POU2-OR102',
    'Goblet-POU2-OR109',
    'Goblet-POU2-OR43',
    'Goblet-POU2-OR72'
  )]
```

```{r}
col1 <- c('1' = 'red', '2' = 'green') # pouch 2 (1) vs ac (2)
col2 <- c('0' = '#ffffe5', '1' = '#6a3d9a', '2' = '#fddaec') # shared with smillie inflammed(1), healthy (2)
col3 <- c('0' = '#ffffe5', '1' = '#4292c6', '2' = '#35978f') # region ti (1) ac (2), other (0)
anno1 <- rowAnnotation(
  bar2 = anno_block(gp = gpar(fill = col2[levels(df$levels) %>% substr(., 2, 2)]),
                    width = unit(3, "mm")),
  bar3 = anno_block(gp = gpar(fill = col3[levels(df$levels) %>% substr(., 3, 3)]),
                    width = unit(3, "mm")),
  gp = gpar(col = "black")
)

pdf(paste0(out.dir, 'Goblet_sample_heatmap_dense2.pdf'), width = 4.5, height = 8)
p1 <- Heatmap(Average.expression.mtx, col = rc2_rna_heatmap_colors_gradient1,
              cluster_columns = F, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, show_row_names = F,
              
              row_split = df$levels,
              
              row_title = NULL,
              row_gap = unit(1, "mm"), column_gap = unit(0, "mm"), 
              border = T,
              border_gp = gpar(col = "black", lty = 1, lwd = 0),
              
              heatmap_legend_param = list(title = "Mean expression z score"),
              use_raster = F,
              right_annotation = anno1)


print(p1)
dev.off()

# please manually do it in AI: 45   9  27 386  49 254   3  15  11  21 353 269 
```























