---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
library(limma)
library(edgeR)
library(variancePartition)
library(BiocParallel)
library(tidyverse)

source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('/project/gca/yuzhao1/work/manu/rc2/scripts/rna_annotation_markers.R')
source('/project/gca/yuzhao1/work/manu/rc2/scripts/umap_colors.R')
source('/project/gca/yuzhao1/scripts/seurat/deg_pseudobulk.R')
out.dir <- '/project/gca/yuzhao1/work/manu/rc2/plots/'
```

```{r, include = F, eval=F}
# union <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/gut_filtered.rds')
epithelial <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/epithelial3.rds')
```

### PP_EC1vsPOU_EC1

```{r}
seurat <- subset(epithelial, cells = Cells(epithelial)[epithelial$anno1 %in% c('EC1-1', 'EC1-2', "EC2-1", "EC2-2")])
seurat$anno1[seurat$anno1 %in% c("EC1-1", "EC1-2") & seurat$biopsy_location =='POU'] <- 'EC-POU1'
seurat$anno1[seurat$anno1 %in% c("EC2-1", "EC2-2") & seurat$biopsy_location =='POU'] <- 'EC-POU2'
seurat$anno1[seurat$anno1 %in% c("EC1-1", "EC1-2") & seurat$biopsy_location =='PP'] <- 'EC-PP'
seurat$anno1[seurat$anno1 %in% c("EC2-1", "EC2-2") & seurat$biopsy_location =='PP'] <- 'EC-PP'
seurat$anno1[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='TI'] <- 'EC-TI'
seurat$anno1[seurat$anno1 %in% c("EC1-1", "EC1-2", "EC2-1", "EC2-2") & seurat$biopsy_location =='AC'] <- 'EC-AC'
```


```{r}
seurat <- subset(seurat, cells = Cells(seurat)[seurat$anno1 %in% c('EC-POU2', 'EC-PP')])
seurat$anno1.sub <- paste0(seurat$biopsy_location,'_',seurat$anno1)
seurat$anno1 <- 'EC'
unique(seurat$anno1)
unique(seurat$anno1.sub)
table(seurat@meta.data[, c('Patient_ID', 'anno1.sub')])
```


```{r}
de_results <- de_genes(seurat_input = seurat,
                                 classification = 'anno1',
                                 model_formula = ~  anno1.sub + (1|Patient_ID),
                                 maineffect = 'anno1.sub',
                                 pseudo_factors = c('anno1.sub', 'Patient_ID'))
```

```{r}
saveRDS(de_results ,'~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_PP_ECvsPOU_EC2.rds')
```

```{r}
de_results <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_PP_ECvsPOU_EC2.rds')

topTable(de_results[["EC"]],
         coef="anno1.subPP_EC-PP",
         p.value = 0.05,
         sort.by = 'logFC',
         number = 10000)
```



```{r}
# pathway enrichment
source('~/yuzhao1/scripts/deg_dep_utils.R')
de_results  <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/de_results_PP_ECvsPOU_EC2.rds')
```


```{r}
# to visualize genes (p<0.001)
fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPP_EC-PP",
  p.value = 0.05,
  sort.by = 'logFC',
  number = 10000
)
# filter genes
fclist <- fclist[fclist$AveExpr > 5, ]
genes.PP_ECvsPOU_EC2 <- rownames(fclist)[order(fclist$logFC, decreasing = T)[1:50]]
genes.POU_EC2vsPP_EC <- rownames(fclist)[order(fclist$logFC, decreasing = F)[1:50]]
View(fclist)
```

```{r}
# prepare for enrichment (p<0.05)
fclist <- topTable(
  de_results[["EC"]],
  coef = "anno1.subPP_EC-PP",
  p.value = 0.05,
  sort.by = 'logFC',
  number = 10000
)

Res <- myEnrichGSEA_msigdb(GetGenelist(fclist))  ## return a list; each element is a msigdb set (e.g. C8)
resDf <- do.call("rbind", lapply(Res, function(sobj) sobj@result))

saveRDS(resDf ,'~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/resDf_PP_ECvsPOU_EC2.rds')
```

```{r}
resDf <- readRDS('~/gca/yuzhao1/work/final_RC2rna/deg/epithelial/ec/pseudobulk/resDf_PP_ECvsPOU_EC2.rds')
View(resDf)
```

```{r}
topTable(de_results[["EC"]],
         coef="anno1.subPP_EC1",
         p.value = 0.05,
         sort.by = 'logFC',
         number = 10000) %>% View()
```













